### PR TITLE
fix all memory leaks in pw program

### LINKED ISSUE #1018: new-delete type mismatch in ModuleESolver
Please refer to [Address Sanitizer Diagnostics](https://deepmodeling.com/abacus-develop/) for details.

### PR DESCRIPTION
**Pull request by Qianruipku**
PW programs have no memory leaks now.
LCAO programs still have a lot of memory leaks.
Fix: #1018

### CODE REVIEW

File: source/main.cpp [hunk 1]
```diff
@@ -15,6 +15,11 @@ int main(int argc, char **argv)
 	DD.init();
 
 #ifdef __MPI
+	MPI_Comm_free(&POOL_WORLD);
+	MPI_Comm_free(&STO_WORLD);
+	MPI_Comm_free(&PARAPW_WORLD);
+	MPI_Comm_free(&GRID_WORLD);
+	MPI_Comm_free(&DIAG_WORLD);
```
Comment (caic99) [inline source/main.cpp]: How about moving this part (together with `MPI_finalize`) to somewhere in module Parallel? Maybe a new function like `Parallel_Global::finalize_mpi`?

**Review by caic99 — APPROVED** [review]

File: source/module_gint/gint.cpp [hunk 2]
```diff
@@ -10,6 +10,17 @@
...
+{
+	if(pvpR_alloc_flag)
+	{
+		for(int is =0;is<GlobalV::NSPIN;is++)
+		{
+			delete[] pvpR_reduced[is]; 
+		}
+		delete[] pvpR_reduced;
+	}
+}
```
Comment (caic99) [inline source/module_gint/gint.cpp]: Hi @Qianruipku ,
Could you identify from the report where was `pvpR_reduced` allocated? This free operation should correspond to its allocation.

**Review by caic99 — CHANGES_REQUESTED** [review]

File: source/module_gint/gint.cpp (hunk 2 above)
Comment (caic99) [reply source/module_gint/gint.cpp]: Sorry for late reply, because I didn't realize `gint_k` is a derived class of `gint` at first.

Comment (Qianruipku) [reply source/module_gint/gint.cpp]: It is allocated in functions of gint_k. Only if is allocated, the variable "pvpR_alloc_flag" is true.

Comment (caic99) [reply source/module_gint/gint.cpp]: I see. I suggest doing changes on destructor of `Gint_k`.

```c++
Gint_k::~Gint_k()
{
    Gint_k::destroy_pvpR();
}
```

Comment (Qianruipku) [reply source/module_gint/gint.cpp]: I think it's better to deallocated in the destructor of `Gint`. `pvpR_reduced` is the member of `Gint`. `Gint` can also allocate `pvpR_reduced` in the future.

Comment (caic99) [reply source/module_gint/gint.cpp]: > I think it's better to deallocated in the destructor of `Gint`. 

`Gint_k::destroy_pvpR()` is a implemented function in `Gint_k`. I still think it's better to put the deallocation at the corresponding part of its allocation, which is in `Gint_k`.

> `pvpR_reduced` is the member of `Gint`. 

@wenfei-li It seems that `Gint::cal_gint` is never used, also its member `pvpR_reduced`? Is this appropriate?

>`Gint` can also allocate `pvpR_reduced` in the future.

Then maybe we could deallocated in the destructor of `Gint` then.

Comment (wenfei-li) [reply source/module_gint/gint.cpp]: It is indeed better to put it in the destructor of gint_k, since pvpR is only used in multi-k calculations. pvpR will never be used in gint_gamma, since there is no need for that.

Comment (wenfei-li) [reply source/module_gint/gint.cpp]: > > I think it's better to deallocated in the destructor of `Gint`.
> 
> `Gint_k::destroy_pvpR()` is a implemented function in `Gint_k`. I still think it's better to put the deallocation at the corresponding part of its allocation, which is in `Gint_k`.
> 
> > `pvpR_reduced` is the member of `Gint`.
> 
> @wenfei-li It seems that `Gint::cal_gint` is never used, also its member `pvpR_reduced`? Is this appropriate?
> 
> > `Gint` can also allocate `pvpR_reduced` in the future.
> 
> Then maybe we could deallocated in the destructor of `Gint` then.
ay
Why do you say cal_gint and pvpR are not used? They are used in lots of places ...

File: source/module_gint/gint_k_pvpr.cpp [hunk 3]
```diff
@@ -53,7 +53,7 @@ void Gint_k::destroy_pvpR(void)
     
     if(!pvpR_alloc_flag)
     {
-        ModuleBase::WARNING_QUIT("Gint_k::destroy_pvpR","<phi_0i | V | phi_Rj> matrix has not been allocated yet!");
```
Comment (wenfei-li) [inline source/module_gint/gint_k_pvpr.cpp:56]: why are we removing this warning message?

Comment (caic99) [reply source/module_gint/gint_k_pvpr.cpp:56]: This is "warning and quit". If it's not allocated, terminating the program is overkill.

File: source/module_gint/gint.cpp (hunk 2 above)
Comment (caic99) [reply source/module_gint/gint.cpp]: > Why do you say cal_gint and pvpR are not used? They are used in lots of places ...

I mean in `Gint`, but not its derived class.

Comment (wenfei-li) [reply source/module_gint/gint.cpp]: > > Why do you say cal_gint and pvpR are not used? They are used in lots of places ...
> 
> I mean in `Gint`, but not its derived class.

I see. Indeed the class Gint is not useful in its own right ... only gint_gamma and gint_k are used

File: source/module_gint/gint.cpp [hunk 4]
```diff
@@ -10,6 +10,9 @@
 #ifdef __MKL
 #include <mkl_service.h>
 #endif
+Gint::~Gint()
+{
+}
```
Comment (caic99) [inline source/module_gint/gint.cpp]:
```suggestion
```

File: source/module_gint/gint.h [hunk 5]
```diff
@@ -14,6 +14,7 @@
 class Gint
 {
     public:
+    ~Gint();
```
Comment (caic99) [inline source/module_gint/gint.h]:
```suggestion
```

**Review by caic99 — APPROVED** [review]

**Review by dyzheng — APPROVED** [review]
