### PR TITLE
Fix: add a initialization of lmaxmax in UnitTests `cell_unitcell_test_setupcell`

### LINKED ISSUE #2750: Unit Test cell_unitcell_test_setupcell cannot run properly
### Describe the bug

When I run cell_unitcell_test_setupcell (in /abacus-develop/build/source/module_cell/test) as unit test, and find it cannot pass. After checking its output "setup_cell.tmp", I believe it has entered an infinite loop, just like:

                L=1301590, number of zeta = 1
                L=1301591, number of zeta = 1
                L=1301592, number of zeta = 1
                L=1301593, number of zeta = 1
                L=1301594, number of zeta = 1
                L=1301595, number of zeta = 1
                L=1301596, number of zeta = 1
                L=1301597, number of zeta = 1
                L=1301598, number of zeta = 1
                L=1301599, number of zeta = 1
                L=1301600, number of zeta = 1
                L=1301601, number of zeta = 1

Same bug is found in cell_unitcell_test_pw (in /abacus-develop/build/source/module_cell/test_pw).

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

Linux version 5.4.0-86-generic (buildd@lgw01-amd64-041) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) 
Intel oneapi 2021.1.1
libxc-5.2.3
elpa-2021.05.002

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by WHUweiqingzhou**
fix #2750

### CODE REVIEW

File: source/module_cell/test/unitcell_test_setupcell.cpp [hunk 1]
```diff
@@ -61,6 +61,10 @@ class UcellTest : public ::testing::Test
 protected:
 	std::unique_ptr<UnitCell> ucell{new UnitCell};
 	std::string output;
+	void SetUp()
+{
```
Comment (WHUweiqingzhou) [inline source/module_cell/test/unitcell_test_setupcell.cpp]:
```suggestion
    {
```

Comment (hongriTianqi) [inline source/module_cell/test/unitcell_test_setupcell.cpp]:
```suggestion
    {
```

File: source/module_cell/test/unitcell_test_setupcell.cpp [hunk 2]
```diff
@@ -61,6 +61,10 @@ class UcellTest : public ::testing::Test
 protected:
 	std::unique_ptr<UnitCell> ucell{new UnitCell};
 	std::string output;
+	void SetUp()
+    {
+    	ucell->lmaxmax = 2;
+}
```
Comment (WHUweiqingzhou) [inline source/module_cell/test/unitcell_test_setupcell.cpp]:
```suggestion
    }
```

File: source/module_cell/test_pw/unitcell_test_pw.cpp [hunk 3]
```diff
@@ -37,6 +37,10 @@ class UcellTest : public ::testing::Test
 protected:
 	std::unique_ptr<UnitCell> ucell{new UnitCell};
 	std::string output;
+	void SetUp()
+{
```
Comment (WHUweiqingzhou) [inline source/module_cell/test_pw/unitcell_test_pw.cpp]:
```suggestion
    {
```

File: source/module_cell/test_pw/unitcell_test_pw.cpp [hunk 4]
```diff
@@ -37,6 +37,10 @@ class UcellTest : public ::testing::Test
...
+    	ucell->lmaxmax = 2;
+}
```
Comment (WHUweiqingzhou) [inline source/module_cell/test_pw/unitcell_test_pw.cpp]:
```suggestion
    }
```
