### PR TITLE
Fix: Support cell-relax with OFDFT.

### LINKED ISSUE #2855: Cell-relax with OFDFT does not work
### Describe the bug

Cell-relax with OFDFT does not work

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sunliang98**
fix #2855 
Support cell-relax with OFDFT.
Add a corresponding integrate test 921_OF_CR_LDA.

### CODE REVIEW

File: source/module_esolver/esolver_of.cpp [hunk 1]
```diff
@@ -249,8 +249,117 @@ void ESolver_OF::init_after_vc(Input &inp, UnitCell &ucell)
...
+        this->pdirect[is] = new double[this->nrxx];
+        this->precipDir[is] = new std::complex<double>[pw_rho->npw];
+    }
+
+    // ===================================
+    // Initialize KEDF
+    // ===================================
+    this->tf.set_para(this->nrxx, this->dV, GlobalV::of_tf_weight);
+    this->vw.set_para(this->nrxx, this->dV, GlobalV::of_vw_weight);
+    this->wt.set_para(this->nrxx, this->dV, GlobalV::of_wt_alpha, GlobalV::of_wt_beta, this->nelec[0], GlobalV::of_tf_weight, GlobalV::of_vw_weight, GlobalV::of_read_kernel, GlobalV::of_kernel_file, this->pw_rho);
```
Comment (dyzheng) [inline source/module_esolver/esolver_of.cpp]: This line is too long, please format your code (format in line 259 in this file is okay).

Comment (sunliang98) [reply source/module_esolver/esolver_of.cpp]: OK, I have formated it.

**Review by dyzheng — APPROVED** [review]

**Review by YuLiu98 — APPROVED** [review]
