### PR TITLE
Fix incomplete atom map due to the subtle symmetry_prec

### LINKED ISSUE #4739: Large force difference when set different symemtry_prec
### Describe the bug

When I use default symmetry_prec (that is 1e-6) and symmetry_prec 1e-5, the forces are different:
symmetry_prec=1e-6:
```
------------------------------------------------------------------------------------------
 TOTAL-FORCE (eV/Angstrom)
------------------------------------------------------------------------------------------
                       Mo1         0.0000000000         0.0000000000         0.0000000000
                       Mo2         0.0000000000         2.1897877709         0.0000000000
                        S1         0.0000000000        -0.4863101120         0.0541911859
                        S2         0.0000000000        -0.4863101120        -0.0541911859
                        S3         0.0000000000         0.0000000000         0.0541911859
                        S4         0.0000000000         0.0000000000        -0.0541911859
------------------------------------------------------------------------------------------
```

symmetry_prec=1e-5
```
------------------------------------------------------------------------------------------
 TOTAL-FORCE (eV/Angstrom)
------------------------------------------------------------------------------------------
                       Mo1         0.0000000000         0.0000000000         0.0000000000
                       Mo2         0.0000000000         0.0000000000         0.0000000000
                        S1         0.0000000000         0.0000000000         0.0530687862
                        S2         0.0000000000         0.0000000000        -0.0530687862
                        S3         0.0000000000         0.0000000000         0.0530687862
                        S4         0.0000000000         0.0000000000        -0.0530687862
------------------------------------------------------------------------------------------
```

The force of QE:
```
     atom    1 type  1   force =     0.00000000   -0.00000000   -0.00000000
     atom    2 type  1   force =     0.00000000    0.00000000    0.00000000
     atom    3 type  2   force =     0.00000000    0.00000000    0.00195641
     atom    4 type  2   force =    -0.00000000    0.00000000   -0.00195641
     atom    5 type  2   force =     0.00000000   -0.00000000    0.00195641
     atom    6 type  2   force =    -0.00000000   -0.00000000   -0.00195641
```
[a (3).zip](https://github.com/user-attachments/files/16305268/a.3.zip)

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by maki49**
Fix #4739. The problem is that the incomplete atom map found by a subtle symmetry_prec leads to incomplete force symmetrization. My solution is to temporarily increase symmetry_prec when finding the map, and reset `symmetry_prec` to its original value if it succeeds or warning-quit if it fails.

Now the force of the provided case with symmetry_prec=1e-6 is:
```
------------------------------------------------------------------------------------------
 TOTAL-FORCE (eV/Angstrom)                                                                
------------------------------------------------------------------------------------------
                       Mo1         0.0000000000         0.0000000000         0.0000000000 
                       Mo2         0.0000000000         0.0000000000         0.0000000000 
                        S1         0.0000000000         0.0000000000         0.0541911857 
                        S2         0.0000000000         0.0000000000        -0.0541911857 
                        S3         0.0000000000         0.0000000000         0.0541911857 
                        S4         0.0000000000         0.0000000000        -0.0541911857 
------------------------------------------------------------------------------------------
```

The remaining difference from symmetry_prec=1e-5 is due to another 2 differences related to symmetry_prec: 
- which k-point of the equivalent k-points is selected as ibz-kpoint (different coordinate can make small difference)
- which grid of charge density is symmetrized

### CODE REVIEW

**Comment by mohanchen** [comment]
1）We need explanations about why the force on y-axis is so large (2.16?) with or without symmetry operations
2)  The solution is temporary, any accumulated defect will potentially cause a wide range of loss in future...
3) The symmetry module is too large, we need some software engineering, expecially I suggest you learning some knowledge of software architecture .
4) It's not healthy to have a module that heavily depends on someone, we need to do some decentralized work.

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 1]
```diff
@@ -1787,13 +1787,54 @@ void Symmetry::set_atom_map(const Atom* atoms)
...
                         break;
                     }
                 }
             }
         }
     }
+    this->reset_atom_map(atoms);
+}
+
+inline bool check_full_atom_map(const std::vector<std::vector<int>>& m)
```
Comment (mohanchen) [inline source/module_cell/module_symmetry/symmetry.cpp:1799]: the code is too long

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 2]
```diff
@@ -1787,13 +1787,54 @@ void Symmetry::set_atom_map(const Atom* atoms)
...
+    if (m.empty()) { return false;
+}
+    for (const auto& v1 : m) { for (const auto& v2 : v1) { if (v2 == -1) { return false; } } }
+    return true;
+}
+
+void Symmetry::reset_atom_map(const Atom* atoms)
+{
+    const double eps_start = this->epsilon;
+    while (!check_full_atom_map(this->isym_rotiat_) && this->epsilon < 100 * eps_start)
```
Comment (mohanchen) [inline source/module_cell/module_symmetry/symmetry.cpp:1810]: 100 is a magic number, the updated symmetrization operation didn't pass any "test set for symmetry"

**Comment by maki49** [comment]
> 1）We need explanations about why the force on y-axis is so large (2.16?) with or without symmetry operations 2) The solution is temporary, any accumulated defect will potentially cause a wide range of loss in future... 3) The symmetry module is too large, we need some software engineering, expecially I suggest you learning some knowledge of software architecture . 4) It's not healthy to have a module that heavily depends on someone, we need to do some decentralized work.

1. The force before symmetrization is even larger (due to the reduced k-point), that's no problem. The problem is that the symmetrization of some atom's force for some symmetry operations are skipped, because under too small symmetry_prec some equivalent atoms (analyzed in the optimized lattice) are judged as non-equivalent (in the STRU-provided lattice, which may need a slightly larger symmetry_prec according to the specific numeric).
2. Do you have any better solution? 
3. OK.
4. OK.

File: source/module_cell/module_symmetry/symmetry.cpp (hunk 2 above)
Comment (maki49) [reply source/module_cell/module_symmetry/symmetry.cpp:1810]: This is a private function finally called in the public function  `analy_sys`, which has been unit-tested.
It's true that 100 has no theoretical foundation. In this only case I've encountered, 2 is enough.

File: source/module_cell/module_symmetry/symmetry.cpp (hunk 1 above)
Comment (maki49) [reply source/module_cell/module_symmetry/symmetry.cpp:1799]: Yes, but I won't do the refactor in this PR.

**Comment by mohanchen** [comment]
After discussion with @maki49 , I think the symmetry_prec parameter may lead to serious bug when the symmetry_prec is 1.0e-6. For example, when the symmetry operations are applied to atomic forces, the summation of forces from different k points may be incomplete, leading to a large value of force (wrong force!!!). In future, we should be very careful to choose the default value of symmetry_prec.

**Review by mohanchen — APPROVED** [review]

**Comment by WHUweiqingzhou** [comment]
Due to the test in #4798, I revert it.
