### PR TITLE
Fix: No warning is given if KPT is ill set

### LINKED ISSUE #4070: No warning given if KPT is ill set
### Describe the bug

When KPT is set as:
```
K_POINTS 
0            
Gamma 
1 1 1
```
no warning is given

### Expected behavior

give warning

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by Luc1anoo**
### Reminder
- [x] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix [#4070](https://github.com/deepmodeling/abacus-develop/issues/4070)

### Unit Tests and/or Case Tests for my changes
Test has been performed on /abacus-develop/examples/scf/lcao_Si2.
When the KPT is well set, no warning occurs.
When the shift of K-mesh is missing, the calculation will continue with warning throwed in warning.log:
 AUTO_SET NBANDS to 0
 K_Vectors::read_kpoints  warning : Missing k-point offsets in the k-points file.

### What's changed?
throw warning when kpoints is ill set

### CODE REVIEW

File: source/module_cell/klist.cpp [hunk 1]
```diff
@@ -308,7 +308,12 @@ bool K_Vectors::read_kpoints(const std::string &fn)
 
         ifk >> nmp[0] >> nmp[1] >> nmp[2];
```
Comment (WHUweiqingzhou) [inline source/module_cell/klist.cpp]: 1. you can add initialization of `koffest` before valuing it. 
2. be clear about format

**Review by WHUweiqingzhou — CHANGES_REQUESTED** [review]
1. you can add initialization of `koffest` before valuing it.
2. be careful about format

File: source/module_cell/klist.cpp [hunk 2]
```diff
@@ -308,7 +308,12 @@ bool K_Vectors::read_kpoints(const std::string &fn)
...
 
-        ifk >> koffset[0] >> koffset[1] >> koffset[2];
+	if (!(ifk >> koffset[0] >> koffset[1] >> koffset[2]))
+        {
+            ModuleBase::WARNING("K_Vectors::read_kpoints", "Missing k-point offsets in the k-points file.");
+	return 0;
```
Comment (WHUweiqingzhou) [inline source/module_cell/klist.cpp]: You cannot `return` here.

**Review by WHUweiqingzhou — APPROVED** [review]
LGTM. Cheers for your first PR.
