### PR TITLE
Fix: various matrix elements calculations in orbital generation

### LINKED ISSUE #3616: Question: unexpected phase exists in `OVERLAP_Q` matrix <psi|jY>, where does it come from?
### Details

@jinzx10 and I find the `OVERLAP_Q` matrix in `orb_matrx*` output files always has a constant phase, for example given, the generation of Si numerical atomic orbital, has real/imag as a uniform value of -2.13. Not sure about whether it will cause some unexpected behavior when generating numerical orbitals.

$\langle\psi_n(\mathbf{k})|j_l\left(q\right) Y_{lm}\rangle =\sum_{\mathbf{G}}{c_{n\mathbf{G}}^{*}(\mathbf{k})\langle \mathbf{G}+\mathbf{k}|j_l\left( q \right) Y_{lm}\rangle}$

$=\sum_{\mathbf{G}}{c_{n\mathbf{G}}^{*}(\mathbf{k})\int{\mathrm{d}\mathbf{r}}e^{-i\mathbf{G}\cdot\mathbf{r}}j_l\left(qr \right) Y_{lm}\left( \hat{\mathbf{r}}\right)}$

$=4\pi\left(-i\right)^l\sum_{\mathbf{G}}{c_{n\mathbf{G}}^{*}(\mathbf{k})Y_{lm}(\hat{\mathbf{G}})\int{\mathrm{d}r\,\,r^2j_l\left( Gr \right) j_l\left( qr \right)}}$

There is not any phase factor can emerge from this formulation.

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

### LINKED ISSUE #3618: Unsatisfactory precision of spherical Bessel basis overlap matrix <jY|jY>
### Details

In spherical-Bessel-based orbital generation, an important quantity is the overlap matrix between pseudo-atomic orbitals of the form

$$
\phi_{lmq}(\mathbf{r}) = j_l(\theta_q^lr/r_{cut})  Y_{lm}(\hat{r})
$$

where $j_l$ is the $l$-th order spherical Bessel function, $\theta_q^l$ is the $q$-th zero of $j_l$ and $r_{cut}$ is the cutoff radius. Given the above form, pseudo-atomic orbitals centered on the same atom should be orthogonal to each other. In particular, orbitals with the same $(l, m)$ but different $q$ are mutually orthogonal due to (see, e.g., Arfken et al, Mathematical Methods for Physicists, 7ed, p.704)

$$
\int_{0}^{r_{cut}} j_l(\theta_p^l/r_{cut}) j_l(\theta_q^l/r_{cut}) r^2 \textrm{d}r = \frac{r_{cut}^3}{2}[j_{l+1}(\theta_p^l)]^2 \delta_{pq}
$$

When generating orbitals, ABACUS computes the above overlap integral in a plane wave basis (see module_io/numerical_basis.cpp and module_io/bessel_basis.cpp). It was found that the overlaps computed this way are merely accurate up to 2-3 digits. Take $r_{cut}=6$, $l=0$ as an example, here's what I find for the diagonal elements ($p=q$ in the above formula):

```
abacus =  [11.2286333   2.76279049  1.21788338  0.68794165  0.43991652  0.30545505
  0.22389927  0.17117827  0.13542846  0.10935793  0.09027062  0.07595007
  0.0645185   0.05555011  0.04834646  0.04229492  0.0371663   0.0324635
  0.01803246]

exact =  [10.94268783  2.73567196  1.2158542   0.68391799  0.43770751  0.30396355
  0.22332016  0.1709795   0.13509491  0.10942688  0.09043544  0.07599089
  0.06474963  0.05583004  0.04863417  0.04274487  0.03786397  0.03377373
  0.03031215]
```

Relative errors are usually larger for those with large wave numbers and/or higher angular momentum. For $l=2$,

```
abacus =  [2.99362726e+00 1.26277216e+00 7.01621082e-01 4.45421465e-01
 3.08077783e-01 2.25262960e-01 1.72001003e-01 1.35937846e-01
 1.09673248e-01 9.05111864e-02 7.60977649e-02 6.46332924e-02
 5.56446757e-02 4.84185160e-02 4.23436108e-02 3.72098421e-02
 3.24975816e-02 1.84669827e-02 1.48580134e-03]

exact =  [2.95984447 1.25833013 0.69716037 0.44309456 0.30655182 0.22471412
 0.17179542 0.13560378 0.10976051 0.09066319 0.07615163 0.0648663
 0.05591676 0.04869996 0.04279569 0.03790384 0.03380544 0.0303377
 0.02737752]
```
As shown above, the relative error of the last element is huge.

Orthogonality isn't well preserved either. For instance, the overlap between $l=0, p=0$ and $l=0, p=0, 1, ...18$ is found to be

```
[ 1.12286333e+01 -1.89601178e-02  6.16002275e-03 -2.81478429e-03
   2.08540528e-03 -1.42883893e-03  1.09471966e-03 -7.79775262e-04
   6.00822362e-04 -4.47178256e-04  3.19165797e-04 -2.41705073e-04
   1.60822425e-04 -9.85552866e-05  2.98149927e-05  2.63160566e-05
  -9.46393546e-05  1.97200773e-04 -5.76675434e-04]
```

which should be all zero except the first element.

### Task list for Issue attackers (only for developers)

- [ ] Reproduce the performance issue on a similar system or environment.
- [X] Identify the specific section of the code causing the performance issue.
- [X] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified performance issue.
- [ ] Implement the chosen solution to address the performance issue.
- [ ] Test the implemented solution to ensure it improves performance without introducing new issues.
- [ ] Optimize the solution if necessary, considering trade-offs between performance and other factors (e.g., code complexity, readability, maintainability).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Merge the improved solution into the main codebase and notify the issue reporter.

### PR DESCRIPTION
**Pull request by jinzx10**
### Reminder
- [x] Have you linked an issue with this pull request?
- [x] Have you added adequate unit tests and/or case tests for your pull request?
- [x] Have you noticed possible changes of behavior below or in the linked issue?
- [x] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #3618 
Resolve #3616

### Unit Tests and/or Case Tests for my changes
- A unit test for two-center integral <jY|jY> is added

### What's changed?
- The algorithm for computing <jY|jY> in orbital generation is switched from a summation in plane-wave basis to two-center integration. This change is expected to bring 2-3 more significant digits. A side effect of this change is that the previous code missed a factor of 2*pi/lat0 in several places, which resulted in an effective 10x weight for the gradient term in spillage. After this change, the same spillage optimization would need to manually set the weight to reproduce previous calculations.
- a complex phase in the plane-wave explansion in the <mo|jY> calculation is corrected;
- bugs in the polynomial interpolation in bessel_basis.cpp are fixed
- removes the usage of ucell via GlobalC and simplifies several function interfaces in numerical_basis 

### Any changes of core modules? (ignore if not applicable)
No.

### CODE REVIEW

File: source/module_io/numerical_basis.cpp [hunk 1]
```diff
@@ -122,7 +125,38 @@ void Numerical_Basis::output_overlap(const psi::Psi<std::complex<double>>& psi,
...
+                // compute <jY|jY> in plane-wave basis
                 overlap_Sq[ik] = this->cal_overlap_Sq( ik, npw, static_cast<double>(derivative_order), sf, wfcpw);
+#else
+                // compute <jY|jY> with two-center integration
+                assert(derivative_order == 0 || derivative_order == 1);
+                char type = (derivative_order == 0) ? 'S' : 'T';
+                std::vector<int> natom;
+                std::vector<int> lmax;
+                std::vector<std::vector<ModuleBase::Vector3<double>>> tau_cart;
+                for (int it = 0; it < GlobalC::ucell.ntype; ++it)
```
Comment (mohanchen) [inline source/module_io/numerical_basis.cpp]: I would suggest passing GlobalC::ucell into this function instead of directly using GlobalC

File: source/module_io/numerical_basis_jyjy.cpp [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+
+    // build a RadialCollection of spherical Bessel functions
+    double dr = 0.005; // grid spacing for SphbesRadials; smaller for higher precision
+    RadialCollection orb;
+    orb.build(lmax, nbes, rcut, sigma, dr);
+
+    ModuleBase::SphericalBesselTransformer sbt;
+    orb.set_transformer(sbt);
+
+    double rmax = orb.rcut_max() * 2.0;
```
Comment (mohanchen) [inline source/module_io/numerical_basis_jyjy.cpp]: is this "const double"?

File: source/module_io/numerical_basis_jyjy.cpp [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+    int nr = static_cast<int>(rmax / dr) + 1;
+    
+    orb.set_uniform_grid(true, nr, rmax, 'i', true);
+
+    // build the two-center integrator
+    TwoCenterIntegrator intor;
+    intor.tabulate(orb, orb, type, nr, rmax);
+
+    // traverse the vector of composite index (itype, iatom, l, m)
+    int t1, a1, l1, m1, t2, a2, l2, m2;
```
Comment (mohanchen) [inline source/module_io/numerical_basis_jyjy.cpp]: initialize the variables?

File: source/module_io/numerical_basis_jyjy.cpp [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+        std::tie(t1, a1, l1, m1) = *it1;
+        for (auto it2 = mu_index.cbegin(); it2 != mu_index.cend(); ++it2)
+        {
+            std::tie(t2, a2, l2, m2) = *it2;
+            ModuleBase::Vector3<double> dR = R[t2][a2] - R[t1][a1];
+            for (int zeta1 = 0; zeta1 < nbes; ++zeta1)
+            {
+                for (int zeta2 = 0; zeta2 < nbes; ++zeta2)
+                {
+                    double elem;
```
Comment (mohanchen) [inline source/module_io/numerical_basis_jyjy.cpp]: initialize the variable?

File: source/module_io/numerical_basis.cpp (hunk 1 above)
Comment (jinzx10) [reply source/module_io/numerical_basis.cpp]: I definitely agree with this idea! The latest commit changes the all usage of ucell within the NumericalBasis class from GlobalC to function arguments.

File: source/module_io/numerical_basis_jyjy.cpp (hunk 2 above)
Comment (jinzx10) [reply source/module_io/numerical_basis_jyjy.cpp]: Thanks for the advice! const modifier has been added.

File: source/module_io/numerical_basis_jyjy.cpp (hunk 3 above)
Comment (jinzx10) [reply source/module_io/numerical_basis_jyjy.cpp]: Thanks for the advice! These variables are initialized in the latest commit.

**Comment by jinzx10** [comment]
This PR has been converted to a draft since its consequence to subsequent spillage optimization is not fully studied yet. It might be better to merge this PR after sufficient tests on the final orbitals. @kirk0830

File: source/module_io/numerical_basis_jyjy.cpp [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+    for (size_t itype = 0; itype < natom.size(); ++itype)
+    {
+        for (int iatom = 0; iatom < natom[itype]; ++iatom)
+        {
+            for (int l = 0; l <= lmax[itype]; ++l)
+            {
+                for (int M = 0; M < 2*l+1; ++M)
+                {
+                    // convert the "abacus M" to the conventional m
+                    int m = (M % 2 == 0) ? -M/2 : (M+1)/2;
```
Comment (mohanchen) [inline source/module_io/numerical_basis_jyjy.cpp]: add a const for m?

File: source/module_io/numerical_basis_jyjy.cpp [hunk 6]
```diff
@@ -0,0 +1,96 @@
...
+    const char type,
+    const int lmax,
+    const int nbes,
+    const double rcut,
+    const std::vector<std::vector<ModuleBase::Vector3<double>>>& R,
+    const std::vector<index_t> mu_index
+)
+{
+    // allocate output array
+    int nlocal = mu_index.size();
```
Comment (mohanchen) [inline source/module_io/numerical_basis_jyjy.cpp]: const int nlocal?

File: source/module_io/numerical_basis_jyjy.cpp [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+    ModuleBase::ComplexArray overlap_Sq(nlocal, nlocal, nbes, nbes);
+    overlap_Sq.zero_out();
+
+    // build a RadialCollection of spherical Bessel functions
+    double dr = 0.005; // grid spacing for SphbesRadials; smaller for higher precision
```
Comment (mohanchen) [inline source/module_io/numerical_basis_jyjy.cpp]: const double dr ?

File: source/module_io/test/numerical_basis_test.cpp [hunk 8]
```diff
@@ -0,0 +1,158 @@
...
+
+    for (size_t it = 0; it < natom.size(); ++it)
+    {
+        for (int ia = 0; ia != natom[it]; ++ia)
+        {
+            for (int l = 0; l <= lmax[it]; ++l)
+            {
+                for (int M = 0; M < 2*l+1; ++M)
+                {
+                    int m = (M % 2 == 0) ? -M/2 : (M+1)/2;
```
Comment (mohanchen) [inline source/module_io/test/numerical_basis_test.cpp]: const int m?

File: source/module_io/test/numerical_basis_test.cpp [hunk 9]
```diff
@@ -0,0 +1,158 @@
...
+                    ++idx;
+                }
+            }
+        }
+    }
+}
+
+TEST_F(NumericalBasisTest, cal_overlap_Sq)
+{
+    int lmax = 3;
```
Comment (mohanchen) [inline source/module_io/test/numerical_basis_test.cpp]: const int lmax?

File: source/module_io/numerical_basis_jyjy.cpp (hunk 5 above)
Comment (jinzx10) [reply source/module_io/numerical_basis_jyjy.cpp]: A const qualifiers has been added in the latest commit.

File: source/module_io/numerical_basis_jyjy.cpp (hunk 6 above)
Comment (jinzx10) [reply source/module_io/numerical_basis_jyjy.cpp]: A const qualifiers has been added in the latest commit.

File: source/module_io/numerical_basis_jyjy.cpp (hunk 7 above)
Comment (jinzx10) [reply source/module_io/numerical_basis_jyjy.cpp]: A const qualifiers has been added in the latest commit.

File: source/module_io/test/numerical_basis_test.cpp (hunk 8 above)
Comment (jinzx10) [reply source/module_io/test/numerical_basis_test.cpp]: A const qualifiers has been added in the latest commit.

File: source/module_io/test/numerical_basis_test.cpp (hunk 9 above)
Comment (jinzx10) [reply source/module_io/test/numerical_basis_test.cpp]: A const qualifiers has been added in the latest commit.

**Review by kirk0830 — APPROVED** [review]
The change in bessel_basis is the key of this PR, previous polynomial interpolation is wrongly implemented

**Review by mohanchen — APPROVED** [review]
