### PR TITLE
Test: fix warning in 107_PW_outWfcR

### LINKED ISSUE #2872: 107_PW_outWfcR will be solved
### Describe Current Status and Possible Solution

This issue will be solved. It is splitter from another big issue.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hongriTianqi**
Fix #2872

### CODE REVIEW

**Review by jinzx10 — APPROVED** [review]

File: tests/integrate/tools/catch_properties.sh [hunk 1]
```diff
@@ -253,7 +253,7 @@ if ! test -z "$has_wfc_r"  && [ $has_wfc_r == 1 ]; then
 		exit 1
 	fi
 	nband=$(grep NBANDS OUT.autotest/running_scf.log|awk '{print $3}')
-	allgrid=$(grep "fft grid for wave functions" OUT.autotest/running_scf.log|awk -F "[=,]" '{print $2*$3*$4}')
+	allgrid=$(grep "fft grid for wave functions" OUT.autotest/running_scf.log | awk -F "[=,\[\]]" '{print $3*$4*$5}')
```
Comment (hongriTianqi) [inline tests/integrate/tools/catch_properties.sh]:
```suggestion
allgrid=$(grep "fft grid for wave functions" OUT.autotest/running_scf.log | awk -F "[=,\\\[\\\]]" '{print $3*$4*$5}')
````

**Review by jinzx10 — APPROVED** [review]
