### PR TITLE
Fix: Fix `cal_bandgap` for parallelism of k-points and band.

### LINKED ISSUE #6601: The function `cal_bandgap` does not account for parallelism of k-points and bands
### Describe the bug

The current implementation of `ElecState::cal_bandgap()` does not account for band or k-point parallelism.
Note that this issue does NOT affect plane-wave parallelism.

### Expected behavior

Fix this bug.

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by sunliang98**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #6601 

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
This PR fixes inconsistencies in parallel computation results. Below are two examples demonstrating the improvements:

1. K-points Parallelism (01_PW/004_PW_UPF201_Si, Si)

Before fix:

| kpar | E_bandgap (Ry) |
|------|----------------|
| 1    | 0.0298852541   |
| 2    | 0.1033124558   |
| 3    | 0.1762318244   |

After fix:

| kpar | E_bandgap (Ry) |
|------|----------------|
| 1    | 0.0298852541   |
| 2    | 0.0298852541   |
| 3    | 0.0298852541   |

3. Band Parallelism (11_PW_GPU/001_PW_BPCG_GPU, GaAs, run with CPU)

Before fix:

| nCPU | E_bandgap (Ry) |
|------|----------------|
| 1    | 0.0416524880   |
| 4    | inf   |

After fix:

| nCPU | E_bandgap (Ry) |
|------|----------------|
| 1    | 0.0416524880   |
| 4    | 0.0416513276   |

Results are now consistent across different parallel configurations

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

File: source/source_estate/elecstate_energy.cpp [hunk 1]
```diff
@@ -16,25 +17,31 @@ void ElecState::cal_bandgap()
         this->bandgap = 0.0;
         return;
     }
-    // int nbands = PARAM.inp.nbands;
+
     int nbands = this->ekb.nc;
     int nks = this->klist->get_nks();
-    double homo = this->ekb(0, 0);
-    double lumo = this->ekb(0, nbands - 1);
+    double homo = -std::numeric_limits<double>::infinity();
```
Comment (mohanchen) [inline source/source_estate/elecstate_energy.cpp]: use CBM and VBM may be better

**Review by mohanchen — APPROVED** [review]
