### PR TITLE
Fix&Refactor: support naive and complete CIF file I/O interface

### LINKED ISSUE #4998: Bug: broken CIF file output by ABACUS
### Describe the bug

As feedback from user, the STRU.cif output cannot be parsed by ASE `read()` function. Related developer should make sure a standard format of CIF is provided instead of a broken one. Here I copy the error message given by ASE:
OH$0Q9Q}YMJX6T`GIM{V`$P_tmb

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### LINKED ISSUE #5020: Bug: missing whole atom type in ABACUS dumped STRU.cif
### Describe the bug

I have a structure like
image
but the dumped cif is like
image
all the O atoms are absent.
It is a severe bug.

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by kirk0830**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #4998, partially fix #5020 

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

File: source/module_io/cif_io.h [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+#include <vector>
+#include <map>
+
+namespace ModuleIO
+{
+/**
+ * @file cif_io.h
+ * @brief This file contains the implementation of the functions for reading and writing CIF files.
+ * 
+ * Due to the space group and point group symmetry information are not always present,
```
Comment (jinzx10) [inline source/module_io/cif_io.h:14]: This sentence is grammatically incorrect.

File: source/module_io/cif_io.h
Comment (jinzx10) [inline source/module_io/cif_io.h:1]: A few suggestions:
1. There are quite a few grammatical errors in the annotation. They do not necessary convey wrong information but are usually distracting.
2. The detailed introduction of this class does not contain necessary information of this class, but quite a few irrelevant or indirect information. For example, what are the valid keys of "get()", and what's the meaning of its returning values?
3. Several exposed functions does not seem relevant to the purpose of this class, e.g., rad2deg, deg2rad, split_outside_enclose, split_loop_block, build_table, build_block_data, etc. Some of them lack explanations.

Comment (kirk0830) [reply source/module_io/cif_io.h:1]: Thank you for your suggestions. I will correct the grammar of the annotations.

Regarding comment 2, the contents of the CIF file can vary significantly. For example, if it's a CIF file downloaded from the Materials Project, there's always a fixed set of keys. However, if it's from the COD database or elsewhere, the keys present will be different. It seems that only a limited number of keys are common among them. Therefore, I left the get() function there without further description on "what would be valid keys" (because I don't know neither). But it's okay to include these words in the annotation.

For comment 3, yes, I can put them in the private domain.

**Review by mohanchen — APPROVED** [review]

**Comment by QuantumMisaka** [comment]
STRU.cif reading test not passed in ASE, ATOMKIT and VESTA

**Comment by kirk0830** [comment]
> STRU.cif reading test not passed in ASE, ATOMKIT and VESTA

thanks for information, I will fix it.

**Comment by kirk0830** [comment]
now the cif file can be successfully read by ASE, VESTA @QuantumMisaka :
image

**Comment by QuantumMisaka** [comment]
Now, the output STRU.cif can be viewed and used by ATOMKIT and VESTA, but still not ASE. The error message is the same as that issue.

**Comment by kirk0830** [comment]
> Now, the output STRU.cif can be viewed and used by ATOMKIT and VESTA, but still not ASE. The error message is the same as that issue.

@QuantumMisaka could you give me your example?

**Comment by kirk0830** [comment]
> Now, the output STRU.cif can be viewed and used by ATOMKIT and VESTA, but still not ASE. The error message is the same as that issue.

image
seems no problem with ase-3.23.0?

**Comment by QuantumMisaka** [comment]
No problem.
The only subtle thing is that the `STRU.cif` file will be regonized ase ABACUS STRU format when using ASE-ABACUS interface instead of original ASE

**Review by jinzx10 — COMMENTED** [review]
I have no further comment on the code per se, but have a few caveats regarding the general functionality of reading/writing CIF file in abacus. CIF is a standardized file format with at least 2 different versions in use. Each version has its specification that rigorously defines what a valid CIF file should look like. While the present code works for many common CIF files, it seems to me that the parser does not strictly follow the standards, so in theory the parser may fail to read a valid CIF file, or may successfully parse an invalid CIF file.
Given the amount of work of writing a standard-compliant parser, the current parser might be an economic solution. Yet I think the code should state explicitly in the annotation on what specific formats are supported, instead of pretending to be a standard CIF parser, so as to assist future development (if needed).

By the way, if the functionality of UnitCell::print_cell_cif() is completely covered by this new parse, I think the original function should be removed from the code (or labeled deprecated) instead of adding more comments.

**Review by jinzx10 — APPROVED** [review]

**Review by jinzx10 — COMMENTED** [review]
Just a quick question: why print_cell_cif("STRU.cif") in esolver_ks.cpp is moved to esolver_fp.cpp & esolver_lj.cpp?

**Comment by kirk0830** [comment]
> Just a quick question: why print_cell_cif("STRU.cif") in esolver_ks.cpp is moved to esolver_fp.cpp & esolver_lj.cpp?

@jinzx10 because this function is actually designed for outputting the structure calculated on, thus for this purpose, all esolvers should have the identical behavior, including derived classes of esolver_ks, also esolver_of, and other non-dft methods such as lj.

**Review by YuLiu98 — APPROVED** [review]

**Review by jinzx10 — APPROVED** [review]
Just a few marginal points:
1. What happens to Symmetry::inequivalent_atoms() in symmetry.cpp? Why is it removed?
2. There're about 200 lines of code that are commented out in cif_io_test.cpp. Are they potentially useful in the future?

**Comment by kirk0830** [comment]
> Just a few marginal points:
> 
> 1. What happens to Symmetry::inequivalent_atoms() in symmetry.cpp? Why is it removed?

This function was only called in the removed/deprecated function "print_cell_cif". I used to consult with @maki49, she pointed out that this function was wrongly implemented and caused the bug reported in issue #5020, so I also removed that function. In the past this function was used to generate equivalent atomic site information in cif file, while in principle the point group information should appear in cif file together with spacegroup information, but actually ABACUS cannot give it because additional translational symmetry analysis should be performed. The absence of key "_symmetry_space_group_name_H-M" caused crash of parsing ABACUS-dumped cif by ASE and other interfaces as reported in issue #4998.

> 2. There're about 200 lines of code that are commented out in cif_io_test.cpp. Are they potentially useful in the future?

Seems not, I will remove them.
