### PR TITLE
Fix: Incorrect negative signs in length gague RT-TDDFT

### LINKED ISSUE #4587: Negative signs in length gague rt-TDDFT
### Describe the bug

There are two sign mistakes in length gague rt-TDDFT:
1.The first one is in the length gague potential：
$V=-qE \cdot r$
For electron, $q=-e$, so it actually should be written as $V=eE \cdot r$ (SI), or $V=E \cdot r$ (au). While in ABACUS code, it was implemented in form $V=-E \cdot r$ (au).

2.The second one is in the output dipole:
$D=\int q\rho (r)rdr$
The problem $q=-e$ also exist here. It actually should be written as $D=-\int e\rho (r)rdr$.

Well , these two negative signs actually do no harm to the result of length gague TDDFT calculation, since the efield oscillates over time and the mistake in dipole calculation was cancelled by the mistake in potential calculation. But if you want to compare the result with velocity gague or other software's tddft, some physical quantities will be completely opposite.
Figure_1

So I suggest fixing these two negative signs to maintain consistency with other software and velocity gague.

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by AsTonyshment**
### Linked Issue
Fix #4587. Sorry for the delay in addressing this issue; I have been working on partial charge densities for the past two weeks.

### Benchmark
After conducting a brief short-time test, I believe the implementation is now correct.

Velocity gauge dipole
dipole

Length gauge dipole (before fix)
dipole

Length gauge dipole (after fix)
dipole

### CODE REVIEW

**Comment by AsTonyshment** [comment]
Need to change the corresponding integrated tests.

**Review by mohanchen — APPROVED** [review]

File: source/module_elecstate/potentials/H_TDDFT_pw.cpp [hunk 1]
```diff
@@ -249,41 +256,42 @@ void H_TDDFT_pw::update_At()
...
-        istep_int = istep*ncut;
-        dt_int = dt/double(ncut);
+        istep_int = istep * ncut;
+        dt_int = dt / double(ncut);
 
-        //store vext_time for each time point, include the first and last point
-        double* vext_time = new double[ncut+1]();
-        for(int i=0; i<=ncut; i++)
+        // store vext_time for each time point, include the first and last point
+        double* vext_time = new double[ncut + 1]();
```
Comment (mohanchen) [inline source/module_elecstate/potentials/H_TDDFT_pw.cpp]: could you change this to vector instead of new and delete?

File: source/module_io/write_dipole.cpp [hunk 2]
```diff
@@ -43,12 +43,12 @@ void ModuleIO::write_dipole(const double* rho_save,
         {
             for (int i = 0; i < rhopw->nx; i++)
             {
-                dipole_elec_x += rho_save[i * rhopw->ny * rhopw->nz + j * rhopw->nz + k] * i
-                                 * GlobalC::ucell.lat0 * 0.529177 / rhopw->nx;
-                dipole_elec_y += rho_save[i * rhopw->ny * rhopw->nz + j * rhopw->nz + k] * j
-                                 * GlobalC::ucell.lat0 * 0.529177 / rhopw->ny;
-                dipole_elec_z += rho_save[i * rhopw->ny * rhopw->nz + j * rhopw->nz + k] * k
-                                 * GlobalC::ucell.lat0 * 0.529177 / rhopw->nz;
```
Comment (mohanchen) [inline source/module_io/write_dipole.cpp:51]: i * rhopw->ny * rhopw->nz + j * rhopw->nz + k can be calculated once and saved in a variable

**Review by mohanchen — APPROVED** [review]
