### PR TITLE
fix: the bug of possible large movement of atom position caused by periodicity in BFGS method

### LINKED ISSUE #3600: BFGS in ABACUS is incorrect
### Describe the bug

I have tested the relax of some examples  by using BFGS method in ABACUS and by BFGS method in ASE (calculator is abacus). The energy curve by using ABACUS cannot slowly decrease like the energy curve of ASE.

one example 002_pt111 is:
ASE+ABACUS:
68252f428b6b65630d5ea09fb205befd_c679b7ab-59d1-405b-9bf0-138ad1d1d5b9

ABACUS:
ac7709ab1be771df4d6b5e8724cffa95_viSzAcSow9gAAAABJRU5ErkJggg==

Also have tested the code of https://github.com/sunliang98/abacus-develop/tree/hot-fix:
002_pt111

More results are shown in: https://dptechnology.feishu.cn/docx/KmqbdUFP4oi6nyxbW8Jc8l5knff
[bfgs.zip](https://github.com/deepmodeling/abacus-develop/files/14160361/bfgs.zip)

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by pxlxingliang**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #3600

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

File: source/module_relax/relax_old/ions_move_bfgs.cpp [hunk 1]
```diff
@@ -40,7 +40,16 @@ void Ions_Move_BFGS::start(UnitCell& ucell, const ModuleBase::matrix& force, con
...
 
     // use force to setup gradient.
-    Ions_Move_Basic::setup_gradient(ucell, force, this->pos, this->grad);
+    if (first_step)
+    {
+        Ions_Move_Basic::setup_gradient(ucell, force, this->pos, this->grad);
+        first_step = false;
+    }
+    else{
+        double *pos_tmp = new double[3 * ucell.nat];
```
Comment (kirk0830) [inline source/module_relax/relax_old/ions_move_bfgs.cpp]: Maybe I suggest use std::vector here because now it is the time we can gradually get rid of the unsafe raw pointer...

**Comment by kirk0830** [comment]
Cheers, 
but the geometry optimizer looks not quite nice cause there is obviously an inheritance relation between base class `BFGS_Basic` and the `Ions_Move_BFGS` but I doubt a little about if this design is really meaningful.

File: source/module_relax/relax_old/ions_move_bfgs.cpp [hunk 2]
```diff
@@ -40,7 +40,16 @@ void Ions_Move_BFGS::start(UnitCell& ucell, const ModuleBase::matrix& force, con
...
+        Ions_Move_Basic::setup_gradient(ucell, force, pos_tmp, this->grad);
+        delete[] pos_tmp;
```
Comment (caic99) [inline source/module_relax/relax_old/ions_move_bfgs.cpp]:
```suggestion
        std::vector<double> pos_tmp(3 * ucell.nat);
        Ions_Move_Basic::setup_gradient(ucell, force, pos_tmp.data(), this->grad);
```

**Review by kirk0830 — APPROVED** [review]

**Comment by pxlxingliang** [comment]
> Cheers, but the geometry optimizer looks not quite nice cause there is obviously an inheritance relation between base class `BFGS_Basic` and the `Ions_Move_BFGS` but I doubt a little about if this design is really meaningful.

This also confuse me. These codes need be refactored to make the structure clearer.

File: source/module_relax/relax_old/ions_move_bfgs.cpp [hunk 3]
```diff
@@ -40,7 +40,15 @@ void Ions_Move_BFGS::start(UnitCell& ucell, const ModuleBase::matrix& force, con
...
 
     // use force to setup gradient.
-    Ions_Move_Basic::setup_gradient(ucell, force, this->pos, this->grad);
+    if (first_step)
+    {
+        Ions_Move_Basic::setup_gradient(ucell, force, this->pos, this->grad);
+        first_step = false;
+    }
+    else{
+        std::vector<double> pos_tmp(3 * ucell.nat);
```
Comment (dyzheng) [inline source/module_relax/relax_old/ions_move_bfgs.cpp:51]: The pos_tmp looks useless?

Comment (caic99) [reply source/module_relax/relax_old/ions_move_bfgs.cpp:51]: > The pos_tmp looks useless?

@dyzheng used below as buffer

**Review by dyzheng — APPROVED** [review]
LGTM
