### PR TITLE
Fix: stuck when the specified number of atoms is larger than that listed in coordinate block

### LINKED ISSUE #1222: ABACUS gets stuck when the number of atoms differs from the number of coordinates in the STRU
### Describe the bug

It can be reproduced by deleteing the line in italics.
The STRU comes from [abacus-develop/examples/H2O-deepks-pw at develop · deepmodeling/abacus-develop](https://github.com/deepmodeling/abacus-develop/tree/develop/examples/H2O-deepks-pw).

---
ATOMIC_SPECIES
H 1.008 H_ONCV_PBE-1.0.upf
O 15.9994 O_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
H_gga_6au_60Ry_2s1p.orb
O_gga_6au_60Ry_2s2p1d.orb

LATTICE_CONSTANT
10

LATTICE_VECTORS
1 0 0
0 1 0
0 0 1

ATOMIC_POSITIONS
Cartesian

H
0
2
0.2336137046291667 0.8630016418166666 0.7271997623458333 1 1 1
_**0.23417266949166665 0.9245341895916668 0.7207232227333333 1 1 1**_

O
0
1
0.20910677665833333 0.894927691625 0.7301984601833333 1 1 1

---

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by ouqi0711**
This PR fixes the stuck problem when the specified number of atoms is LARGER than that listed in coordinate block. However, no warning information would be given if the specified number of atoms is LESS than that listed in coordinate block, which should be fixed in the future. 
Fix #1222 .

### CODE REVIEW

File: source/module_cell/read_atoms.cpp [hunk 1]
```diff
@@ -603,6 +603,13 @@ bool UnitCell_pseudo::read_atom_positions(std::ifstream &ifpos, std::ofstream &o
 
                                         string tmpid;
                                         tmpid = ifpos.get();
+
+										if( (int)tmpid[0] < 0 )
+										{
+											std::cout << "read_atom_positions, mismatch in atom number for atom type: " << atoms[it].label << std::endl;
+											exit(0);
```
Comment (caic99) [inline source/module_cell/read_atoms.cpp]: Maybe exit a non-zero value for error?
```suggestion
											exit(1); 
```

**Review by caic99 — APPROVED** [review]
