### PR TITLE
Fix HR output in tddft

### LINKED ISSUE #4117: Wrong output Matrices in tddft calculation
### Describe the bug

The output Matrices, H(R),S(R),S(k)，are totally wrong if 'esolver_type=tddft'. It's a problem occurs only in versions later than 3.5.0. Since tddft didn't changed from 3.4.4 to 3.5.0, I guess the reason is that the output function has changed, yet tddft didn't change correspondly. Please fix this. 

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by ESROAMER**
### Linked Issue
Partially Fix #4117 
Due to the type difference, the HR data of tddft correction term must be added independently to get a correct HR matrix. I modified part of the functions "cal_HSR" and "save_HSR" and added a new member "HR_sparse_td_vel" to class "LCAO_Matrix" to fix this.

### CODE REVIEW

File: source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp [hunk 1]
```diff
@@ -877,6 +878,13 @@ void LCAO_Matrix::destroy_HS_R_sparse(void)
         HR_sparse[0].swap(empty_HR_sparse_up);
         HR_sparse[1].swap(empty_HR_sparse_down);
         SR_sparse.swap(empty_SR_sparse);
+        if(GlobalV::ESOLVER_TYPE == "tddft" && elecstate::H_TDDFT_pw::stype ==1)
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp]: we will delete LCAO_matrix.cpp in near future, so please don't add any new codes in LCAO_matri.cpp, find some where or even construct a new class/namespace

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp [hunk 2]
```diff
@@ -368,6 +370,19 @@ void TDEkinetic<OperatorLCAO<std::complex<double>, double>>::contributeHk(int ik
     else{        
         ModuleBase::TITLE("TDEkinetic", "contributeHk");
         ModuleBase::timer::tick("TDEkinetic", "contributeHk");
+        //Save HR_data of tddft if HR output is needed
+        if(output_hR_done <GlobalV::NSPIN && hsolver::HSolverLCAO<std::complex<double>>::out_mat_hsR == 1 && GlobalV::NSPIN!=4)
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: do not use GlobalV, and this line is too complicated

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp [hunk 3]
```diff
@@ -368,6 +370,19 @@ void TDEkinetic<OperatorLCAO<std::complex<double>, double>>::contributeHk(int ik
...
+        {
+            const int spin_now = GlobalV::CURRENT_SPIN;
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: is there a way not to use CURRENT_SPIN ? the variable will be deleted soon

File: source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp [hunk 4]
```diff
@@ -25,12 +26,24 @@ void sparse_format::cal_HSR(
         hamilt::HamiltLCAO<std::complex<double>, double>* p_ham_lcao = 
         dynamic_cast<hamilt::HamiltLCAO<std::complex<double>, double>*>(p_ham);
 
-		sparse_format::cal_HContainer_d(
+        if(GlobalV::ESOLVER_TYPE == "tddft" && elecstate::H_TDDFT_pw::stype ==1)
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp]: do not use GlobalV

File: source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp [hunk 5]
```diff
@@ -232,6 +288,28 @@ void sparse_format::clear_zero_elements(
                 }
             }
         }
+        if(GlobalV::ESOLVER_TYPE == "tddft" && elecstate::H_TDDFT_pw::stype ==1)
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp]: do not use GlobalV

File: source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp (hunk 1 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp]: I see. I have no idea what the new solution without LCAO_Matrix would be. But whether it count in the special case of tddft HR or not, this fix will definitely be conflict with it and will have to be adjusted. This fix was meant to be a tempoary one, so I thought a fix in a consisent form with the original code would be easier to be considered in during the refactoring work. But nevermind, I'll set up a new class to store the data.

File: source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp (hunk 4 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/hamilt_lcaodft/spar_hsr.cpp]: My apologies. I do not know the replacement for "GlobalV::ESOLVER_TYPE", I'll define a new static bool type variable to replace it.

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp (hunk 3 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: Perhaps the function "sparse_format::cal_HContainer_cd" would be Modified or abandoned first? But yes, a small loop could be instead.

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp [hunk 6]
```diff
@@ -29,6 +31,10 @@ TDEkinetic<OperatorLCAO<TK, TR>>::TDEkinetic(LCAO_Matrix* LM_in,
         this->init_td();
         // initialize HR to get adjs info.
         this->initialize_HR(Grid,this->LM->ParaV);
+        if(hsolver::HSolverLCAO<std::complex<double>>::out_mat_hsR == 1)
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: do not let this function depends on the hsolver, can you pass out_mat_hsR in as an input parameter?

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp [hunk 7]
```diff
@@ -368,6 +374,22 @@ void TDEkinetic<OperatorLCAO<std::complex<double>, double>>::contributeHk(int ik
     else{        
         ModuleBase::TITLE("TDEkinetic", "contributeHk");
         ModuleBase::timer::tick("TDEkinetic", "contributeHk");
+        //save HR data for output
+        int spin_tot = this->LM->ParaV->nspin;
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: can use use Parallel Orbitals instead of LM->ParaV? Because we will delete LCAO_matrix soon.

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp [hunk 8]
```diff
@@ -368,6 +374,22 @@ void TDEkinetic<OperatorLCAO<std::complex<double>, double>>::contributeHk(int ik
...
+        if(spin_tot==4);
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp:382]: why there is a ; after if?

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp [hunk 9]
```diff
@@ -368,6 +374,22 @@ void TDEkinetic<OperatorLCAO<std::complex<double>, double>>::contributeHk(int ik
...
+        else if(!output_hR_done && out_mat_R)
+        {
+            for(int spin_now = 0;spin_now < spin_tot;spin_now++)
+            {
+                sparse_format::cal_HContainer_cd(
+                    *(this->LM->ParaV),
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: use pv (pointer of Parallel_Orbitals) instead of LM->Parav

File: source/module_hamilt_lcao/module_tddft/td_velocity.cpp [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+  return;
+}
+TD_Velocity::~TD_Velocity()
+{
+  this->destroy_HS_R_td_sparse();
+}
+
+void TD_Velocity::destroy_HS_R_td_sparse(void)
+{
+  std::map<Abfs::Vector3_Order<int>, std::map<size_t, std::map<size_t, std::complex<double>>>> empty_HR_sparse_td_vel_up;
```
Comment (mohanchen) [inline source/module_hamilt_lcao/module_tddft/td_velocity.cpp:20]: this structure seems too complicated, do you have a better idea?

File: source/module_esolver/esolver_ks_lcao_tddft.cpp [hunk 11]
```diff
@@ -433,7 +434,15 @@ void ESolver_KS_LCAO_TDDFT::update_pot(const int istep, const int iter)
...
 }
 
-
+void ESolver_KS_LCAO_TDDFT::before_scf(const int istep)
+{
+    ESolver_KS_LCAO<std::complex<double>, double>::before_scf(istep);
+    
+    if(TD_Velocity::td_vel_op == nullptr && TD_Velocity::tddft_velocity)
+    {
+        TD_Velocity::td_vel_op = new TD_Velocity();
```
Comment (mohanchen) [inline source/module_esolver/esolver_ks_lcao_tddft.cpp]: It is dangerous to use new here then delete somewhere else, do you have another way not instead of using 'new'?

Comment (ESROAMER) [reply source/module_esolver/esolver_ks_lcao_tddft.cpp]: Ok, I'll place this object inside the class "TDEkinetic" so it would be released at the same time with the operator "TDEkinetic".

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp (hunk 8 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp:382]: It‘s a null statement. Tddft velocity gague do not support the case of "NSPIN==4"  for now. This is just a place prepared for future adjustment.

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp (hunk 6 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: To use as a input parameter is quite hard. I guess I'll just prepare a static copy in my own class.

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp (hunk 7 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: OK, I'll fix this

File: source/module_hamilt_lcao/module_tddft/td_velocity.cpp (hunk 10 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/module_tddft/td_velocity.cpp:20]: Well, just a suggestion. I think the Hcontainer itself is good enough to fit the need of output real-space matrix, no need to pass its data into a high-order map. 
And forgive me for saying this, I won't change this structure for now since I have known you will remove LCAO_Matrix in the future. The whole feature of output sparse matrix, about 1 Class, 10 files and 20 functions are highly bound to the LCAO_Matrix and this complicated structure, so obiviously this whole feature will be refactored in the lately future. I'm not part of this work, so I can't change these files. And I don't want to construct a totally independent output feature knowing that there will be a new universal solution. I'll keep up with the new solution once it comes out. But for now, it has to stay like this.

File: source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp (hunk 1 above)
Comment (mohanchen) [reply source/module_hamilt_lcao/hamilt_lcaodft/LCAO_matrix.cpp]: Great!

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp [hunk 12]
```diff
@@ -185,6 +192,7 @@ void TDEkinetic<OperatorLCAO<TK, TR>>::cal_HR_IJR(const int& iat1,
 template <typename TK, typename TR>
 void TDEkinetic<OperatorLCAO<TK, TR>>::init_td(void)
 {
+    TD_Velocity::td_vel_op = &td_velocity;
     //calculate At in cartesian coorinates.
 	double l_norm[3]={GlobalC::ucell.a1.norm() ,GlobalC::ucell.a2.norm() ,GlobalC::ucell.a3.norm()};
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: Can you avoid using GlobalC::ucell?

File: source/module_hamilt_lcao/module_tddft/td_velocity.cpp (hunk 10 above)
Comment (mohanchen) [reply source/module_hamilt_lcao/module_tddft/td_velocity.cpp:20]: OK, fair enough.

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp (hunk 12 above)
Comment (ESROAMER) [reply source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/td_ekinetic_lcao.cpp]: Ok, I'll remove the other GlobalC or GlobalV in these files as well.

**Review by mohanchen — APPROVED** [review]
