### PR TITLE
Resolve the segmentation fault occurring in the pw float implementation

### LINKED ISSUE #6111: Bug: Please enable floatfftw in the cmake to use float fft when precision is set to single using GPU
### Describe the bug

I use this INPUT file to test my build from source code: 
```text
INPUT_PARAMETERS
#Parameters	(General)
calculation             scf
pseudo_dir		.
orbital_dir 		.
ntype 1
#Parameters (Accuracy)
symmetry                1
basis_type		pw	# PW; LCAO in pw; LCAO
ecutwfc			100	# energy cutoff for wave functions
scf_nmax		100
scf_thr 1e-6 #1e-5
kspacing 0.05
cal_force 1
cal_stress 1
smearing_method  gauss
smearing_sigma 0.015
mixing_type broyden
mixing_beta 0.3 

ks_solver bpcg

device gpu
precision single
```
But it cannot run and throws a  error shown : `Please enable floatfftw in the cmake to use float fft`

### Expected behavior

_No response_

### To Reproduce

I build abacus from source code using toolchain:
file `toolchain_gnu.sh`:
```shell
#!/bin/bash
#SBATCH -J install
#SBATCH -N 1
#SBATCH -n 16
#SBATCH -o compile.log
#SBATCH -e compile.err

# JamesMisaka in 2023-09-16
# install abacus dependency by gnu-toolchain
# one can use mpich or openmpi.
# openmpi will be faster, but not compatible in some cases.
# libtorch and libnpy are for deepks support, which can be =no
# if you want to run EXX calculation, you should set --with-libri=install
# mpich (and intel toolchain) is recommended for EXX support
# gpu-lcao supporting modify: CUDA_PATH and --enable-cuda
# export CUDA_PATH=/usr/local/cuda

./install_abacus_toolchain.sh \
--with-gcc=system \
--with-intel=no \
--with-openblas=install \
--with-openmpi=install \
--with-cmake=install \
--with-scalapack=install \
--with-libxc=install \
--with-fftw=install \
--with-elpa=install \
--with-cereal=install \
--with-rapidjson=install \
--with-libtorch=install \
--with-libnpy=install \
--with-libri=install \
--with-libcomm=install \
--with-4th-openmpi=no \
--enable-cuda \
--gpu-ver=120 \
| tee compile.log
# to use openmpi-version4: set --with-4th-openmpi=yes
# to enable gpu-lcao, add the following lines:
# --enable-cuda \
# --gpu-ver=75 \ 
# one should check your gpu compute capability number 
# and use it in --gpu-ver
```

and file `build_abacus_gnu.sh`:
```shell
#!/bin/bash
#SBATCH -J build
#SBATCH -N 1
#SBATCH -n 16
#SBATCH -o install.log
#SBATCH -e install.err
# JamesMisaka in 2025.03.09

# Build ABACUS by gnu-toolchain

# module load openmpi

ABACUS_DIR=..
TOOL=$(pwd)
INSTALL_DIR=$TOOL/install
source $INSTALL_DIR/setup
cd $ABACUS_DIR
ABACUS_DIR=$(pwd)

BUILD_DIR=build_abacus_gnu
rm -rf $BUILD_DIR

PREFIX=$ABACUS_DIR
LAPACK=$INSTALL_DIR/openblas-0.3.28/lib
SCALAPACK=$INSTALL_DIR/scalapack-2.2.1/lib
ELPA=$INSTALL_DIR/elpa-2025.01.001/nvidia # for gpu-lcao
FFTW3=$INSTALL_DIR/fftw-3.3.10
CEREAL=$INSTALL_DIR/cereal-1.3.2/include/cereal
LIBXC=$INSTALL_DIR/libxc-7.0.0
RAPIDJSON=$INSTALL_DIR/rapidjson-1.1.0/
LIBRI=$INSTALL_DIR/LibRI-0.2.1.0
LIBCOMM=$INSTALL_DIR/LibComm-0.1.1
LIBTORCH=$INSTALL_DIR/libtorch-2.1.2/share/cmake/Torch
LIBNPY=$INSTALL_DIR/libnpy-1.0.1/include
# DEEPMD=$HOME/apps/anaconda3/envs/deepmd # v3.0 might have problem

cmake -B $BUILD_DIR -DCMAKE_INSTALL_PREFIX=$PREFIX \
        -DCMAKE_CXX_COMPILER=g++ \
        -DMPI_CXX_COMPILER=mpicxx \
        -DLAPACK_DIR=$LAPACK \
        -DSCALAPACK_DIR=$SCALAPACK \
        -DELPA_DIR=$ELPA \
        -DFFTW3_DIR=$FFTW3 \
        -DCEREAL_INCLUDE_DIR=$CEREAL \
        -DLibxc_DIR=$LIBXC \
        -DENABLE_LCAO=ON \
        -DENABLE_LIBXC=ON \
        -DUSE_OPENMP=ON \
        -DUSE_ELPA=ON \
        -DENABLE_RAPIDJSON=ON \
        -DRapidJSON_DIR=$RAPIDJSON \
        -DUSE_CUDA=ON \
        -DENABLE_DEEPKS=1 \
        -DTorch_DIR=$LIBTORCH \
        -Dlibnpy_INCLUDE_DIR=$LIBNPY \
        -DENABLE_LIBRI=ON \
        -DLIBRI_DIR=$LIBRI \
        -DLIBCOMM_DIR=$LIBCOMM \
# 	      -DDeePMD_DIR=$DEEPMD \
        #-DENABLE_CUSOLVERMP=ON \
        #-D CAL_CUSOLVERMP_PATH=/opt/nvidia/hpc_sdk/Linux_x86_64/2x.xx/math_libs/1x.x/targets/x86_64-linux/lib

# # add mkl env for libtorch to link
# if one want to install libtorch, mkl should be load in build process
# for -lmkl when load libtorch
# module load mkl

# if one want's to include deepmd, your system gcc version should be >= 11.3.0 for glibc requirements

cmake --build $BUILD_DIR -j `nproc` 
cmake --install $BUILD_DIR 2>/dev/null

# generate abacus_env.sh
cat << EOF > "${TOOL}/abacus_env.sh"
#!/bin/bash
source $INSTALL_DIR/setup
export PATH="${PREFIX}/bin":\${PATH}
EOF

# generate information
cat << EOF
========================== usage =========================
Done!
To use the installed ABACUS version
You need to source ${TOOL}/abacus_env.sh first !
"""
EOF
```

### Environment

OS: Ubuntu 24.04.2 LTS on Windows 10 x86_64
CPU: AMD Ryzen 9 7950X3D (32) @ 4.192GHz
GPU: 2950:00:00.0 Microsoft Corporation Basic Render Driver (5090D on windows)

### Additional Context

if the precision is set to double(by default) this program runs normally.
Additionally, when I install abacus from conda-forge, single precision can run, but in the 10th or 11th loop, the RAM usage rises suddenly(normally 4G, but rises above RAM limit then in a few seconds), and killed by system

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by A-006**
### Linked Issue
Fix #6111

### Unit Tests and/or Case Tests for My Changes
- Added unit tests for the pw_basis float type. 
- Included integration tests for the pw_basis float type.

### What's Changed?
- Fixed a bug in the runtime handling of the pw_basis float type.
- Enabled GPU support for pw_basis without requiring the compilation flag ENABLE_FFTW_FLOAT.
- ATTENTION!!! In order to reduce the test time of the GPU/CPU,i just add the PW_CG PW_CG_GPU float type to test the float version FFT  can be normally used.

### CODE REVIEW

File: source/module_base/test/math_chebyshev_test.cpp [hunk 1]
```diff
@@ -625,6 +625,8 @@ TEST_F(MathChebyshevTest, tracepolyA_float)
 
 TEST_F(MathChebyshevTest, checkconverge_float)
 {
+    #ifdef __MPI
+    #undef __MPI
```
Comment (mohanchen) [inline source/module_base/test/math_chebyshev_test.cpp:626]: do not write this kind of code #undef__MPI

File: tests/integrate/102_PW_BPCG_GPU_float/README [hunk 2]
```diff
@@ -0,0 +1,9 @@
+This test for:
```
Comment (mohanchen) [inline tests/integrate/102_PW_BPCG_GPU_float/README]: this is not README

File: tests/integrate/102_PW_CG_float/README [hunk 3]
```diff
@@ -0,0 +1,8 @@
+This test for:
+*Si-diamond
+*just gamma point
+*old upf pseudopotential
+*smearing_method default
+*ks_solver cg
+*precison    float
+!!!!!!!WRONG!!!!!!!
```
Comment (mohanchen) [inline tests/integrate/102_PW_CG_float/README]: why there is a "WRONG" here?

File: source/module_esolver/esolver_fp.cpp [hunk 4]
```diff
@@ -24,17 +24,27 @@ namespace ModuleESolver
...
-
-    pw_rho = new ModulePW::PW_Basis_Big(fft_device, PARAM.inp.precision);
+    if(PARAM.inp.precision == "single" || PARAM.inp.precision == "mixing")
+    {
+        fft_precsion = "mixing";
+    }else{
+        fft_precsion = "double";
+    }
+    #if (not defined(__ENABLE_FLOAT_FFTW) and (defined(__CUDA) || defined(__RCOM)))
+        if (fft_device == "gpu")
```
Comment (mohanchen) [inline source/module_esolver/esolver_fp.cpp:61]: add braces after if

File: source/module_esolver/esolver_fp.cpp [hunk 5]
```diff
@@ -24,17 +24,27 @@ namespace ModuleESolver
 ESolver_FP::ESolver_FP()
 {
     std::string fft_device = PARAM.inp.device;
-
+    std::string fft_precsion;
```
Comment (mohanchen) [inline source/module_esolver/esolver_fp.cpp]: pack the fft code to somewhere else

File: source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt [hunk 6]
```diff
@@ -26,4 +27,31 @@ AddTest(
 	TARGET radial_proj_test
 	LIBS parameter  base device ${math_libs}
 	SOURCES radial_proj_test.cpp ../radial_proj.cpp
+)
+
+AddTest(
```
Comment (mohanchen) [inline source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt:32]: what is this test?

Comment (A-006) [reply source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt:32]: > what is this test?

This code is intended to test the structure_factor module found in (source/module_hamilt_pw/hamilt_pwdft/structure_factor.h). Currently, there is no unit test available for this class. If a unit test had been in place, we could have prevented this issue from arising. Therefore, I have added a unit test to avoid similar problems in the future.

File: tests/integrate/102_PW_CG_float/README (hunk 3 above)
Comment (A-006) [reply tests/integrate/102_PW_CG_float/README]: I use the double type as the template.now the WRONG has been removed in both float/double type.

File: source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt (hunk 6 above)
Comment (A-006) [reply source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt:32]: This code is intended to test the structure_factor module found in (source/module_hamilt_pw/hamilt_pwdft/structure_factor.h). Currently, there is no unit test available for this class. If a unit test had been in place, we could have prevented this issue from arising. Therefore, I have added a unit test to avoid similar problems in the future.

File: source/module_base/test/math_chebyshev_test.cpp (hunk 1 above)
Comment (A-006) [reply source/module_base/test/math_chebyshev_test.cpp:626]: Fine, I've changed it to another approach. The reason for the MPI definition issue is that the checkconverge function does not support MPI types in this test. However, other tests in this file require the MPI definition. Therefore, I added an #undef directive before the checkconverge function like the double version(source/module_base/test/math_chebyshev_test.cpp:340) .

File: source/module_esolver/esolver_fp.cpp (hunk 4 above)
Comment (A-006) [reply source/module_esolver/esolver_fp.cpp:61]: The barces have been added.

File: tests/integrate/102_PW_BPCG_GPU_float/README (hunk 2 above)
Comment (A-006) [reply tests/integrate/102_PW_BPCG_GPU_float/README]: Accurately, I implemented the integration test for the first time. However, I am unsure about how to add the README. I encountered this README which has been referenced from PW_BPCG_GPU.

File: source/module_esolver/esolver_fp.cpp (hunk 5 above)
Comment (A-006) [reply source/module_esolver/esolver_fp.cpp]: Fine, but actually, this fft_precision is only used to determine the initialization of PW_BASIS. I prefer adding it here. Since it can also be set in the initialization of PW_BASIS, I move it to PW_BASIS.

File: tests/integrate/102_PW_DS_davsubspace_float/README [hunk 7]
```diff
@@ -0,0 +1,8 @@
+This test for:
+*Si-diamond
+*just gamma point
+*old upf pseudopotential
+*smearing_method default
+*ks_solver dav_subspace
+*precison    float
+!!!!!!!WRONG!!!!!!!
```
Comment (mohanchen) [inline tests/integrate/102_PW_DS_davsubspace_float/README]: here is another "WRONG", please remove it

File: tests/integrate/102_PW_DA_davidson_float/threshold [hunk 8]
```diff
@@ -0,0 +1,5 @@
+# Float type has different eneygy with the double type
```
Comment (mohanchen) [inline tests/integrate/102_PW_DA_davidson_float/threshold]: use correct english

File: tests/integrate/102_PW_DA_davidson_float/threshold [hunk 9]
```diff
@@ -0,0 +1,5 @@
...
+# this intergate is to test the function of
```
Comment (mohanchen) [inline tests/integrate/102_PW_DA_davidson_float/threshold]: use correct english

File: tests/integrate/102_PW_DA_davidson_float/README [hunk 10]
```diff
@@ -0,0 +1,8 @@
+This test for:
+*Si-diamond
+*just gamma point
+*old upf pseudopotential
+*smearing_method default
+*ks_solver dav
+*precison    float
+!!!!!!!WRONG!!!!!!!
```
Comment (mohanchen) [inline tests/integrate/102_PW_DA_davidson_float/README]: here is another "WRONG"

File: tests/integrate/102_PW_DA_davidson_GPU_float/README [hunk 11]
```diff
@@ -0,0 +1,9 @@
+This test for:
```
Comment (mohanchen) [inline tests/integrate/102_PW_DA_davidson_GPU_float/README]: do not write this kind of README

File: tests/integrate/102_PW_CG_float/threshold [hunk 12]
```diff
@@ -0,0 +1,5 @@
+# Float type has different eneygy with the double type
```
Comment (mohanchen) [inline tests/integrate/102_PW_CG_float/threshold]: use correct english

File: tests/integrate/102_PW_DS_davsubspace_float/README (hunk 7 above)
Comment (A-006) [reply tests/integrate/102_PW_DS_davsubspace_float/README]: I have revised the README to another format, incorporating modifications to the existing content and adding parameters for precision and device type.

File: tests/integrate/102_PW_DA_davidson_float/threshold (hunk 9 above)
Comment (A-006) [reply tests/integrate/102_PW_DA_davidson_float/threshold]: I have changed the threshold comments to emphasize that this test is designed to evaluate the functionality

File: tests/integrate/102_PW_DA_davidson_float/threshold (hunk 8 above)
Comment (A-006) [reply tests/integrate/102_PW_DA_davidson_float/threshold]: I have changed the threshold comments to emphasize that this test is designed to evaluate the functionality

File: tests/integrate/102_PW_CG_float/threshold (hunk 12 above)
Comment (A-006) [reply tests/integrate/102_PW_CG_float/threshold]: I have changed the threshold comments to emphasize that this test is designed to evaluate the functionality

File: tests/integrate/102_PW_DA_davidson_float/README (hunk 10 above)
Comment (A-006) [reply tests/integrate/102_PW_DA_davidson_float/README]: The comment has been deleted.

File: tests/integrate/102_PW_DA_davidson_GPU_float/README (hunk 11 above)
Comment (A-006) [reply tests/integrate/102_PW_DA_davidson_GPU_float/README]: I have revised the README to another format.

**Comment by kogareru1z** [comment]
Could you please fix the single-precision calculation issue for the LCAO basis? When I tested with ABACUS 3.9.0.3, I encountered the same problem as with PW, but the error does not occur in version 3.10.

**Comment by A-006** [comment]
> Could you please fix the single-precision calculation issue for the LCAO basis? When I tested with ABACUS 3.9.0.3, I encountered the same problem as with PW, but the error does not occur in version 3.10.

Alright, I'll try to address this issue later. However, I recall that the LCAO basis does not support a single version; I will verify this information

**Comment by A-006** [comment]
> Could you please fix the single-precision calculation issue for the LCAO basis? When I tested with ABACUS 3.9.0.3, I encountered the same problem as with PW, but the error does not occur in version 3.10.

Currently, the LCAO does not support a single version. Could you please inform me whether you intend to use the GPU LCAO single? Actually, this feature will be implemented by my partner. After the pull request (PR) is merged, you will be able to set the GPU LCAO to single; however, in reality, it will run as GPU LCAO double.

**Comment by kogareru1z** [comment]
> > Could you please fix the single-precision calculation issue for the LCAO basis? When I tested with ABACUS 3.9.0.3, I encountered the same problem as with PW, but the error does not occur in version 3.10.
> 
> Currently, the LCAO does not support a single version. Could you please inform me whether you intend to use the GPU LCAO single? Actually, this feature will be implemented by my partner. After the pull request (PR) is merged, you will be able to set the GPU LCAO to single; however, in reality, it will run as GPU LCAO double.

I tested version 3.10 in single precision, but it still runs in double precision. If that’s the case, I don’t need this feature right now. Thank you.

File: source/module_base/test/math_chebyshev_test.cpp [hunk 13]
```diff
@@ -625,6 +625,8 @@ TEST_F(MathChebyshevTest, tracepolyA_float)
 
 TEST_F(MathChebyshevTest, checkconverge_float)
 {
+    #ifdef __MPI
```
Comment (mohanchen) [inline source/module_base/test/math_chebyshev_test.cpp:625]: delete  #ifdef  and then #undef ?

File: source/module_basis/module_pw/module_fft/fft_cpu.cpp [hunk 14]
```diff
@@ -1,5 +1,6 @@
 #include "fft_cpu.h"
 #include "fftw3.h"
+#include "module_base/timer.h"
```
Comment (mohanchen) [inline source/module_basis/module_pw/module_fft/fft_cpu.cpp]: it seems that you didn't use this timer.h, delete it?

File: source/module_basis/module_pw/module_fft/fft_cpu.cpp [hunk 15]
```diff
@@ -347,18 +348,22 @@ void FFT_CPU<double>::fftxyfor(std::complex<double>* in, std::complex<double>* o
     int npy = this->nplane * this->ny;
     if (this->xprime)
     {
+        
         fftw_execute_dft(this->planxfor1, (fftw_complex*)in, (fftw_complex*)out);
+        #pragma omp parallel for
```
Comment (mohanchen) [inline source/module_basis/module_pw/module_fft/fft_cpu.cpp:352]: why do we need openmp in this function, is this modification has effects on efficiency?

File: source/module_esolver/esolver_fp.cpp [hunk 16]
```diff
@@ -23,45 +23,60 @@ namespace ModuleESolver
 
 ESolver_FP::ESolver_FP()
 {
-    std::string fft_device = PARAM.inp.device;
+}
+
+ESolver_FP::~ESolver_FP()
+{
+    if (pw_rho_flag == 1)
```
Comment (mohanchen) [inline source/module_esolver/esolver_fp.cpp]: pw_rho_flag == true may be better?

File: tests/integrate/102_PW_BPCG_GPU_float/README [hunk 17]
```diff
@@ -0,0 +1,55 @@
+# ================================================
```
Comment (mohanchen) [inline tests/integrate/102_PW_BPCG_GPU_float/README]: two lines for README

File: tests/integrate/102_PW_BPCG_float/README
Comment (mohanchen) [inline tests/integrate/102_PW_BPCG_float/README:1]: two lines

File: tests/integrate/102_PW_CG_GPU_float/README
Comment (mohanchen) [inline tests/integrate/102_PW_CG_GPU_float/README:1]: two lines

File: tests/integrate/102_PW_CG_float/README
Comment (mohanchen) [inline tests/integrate/102_PW_CG_float/README:1]: two lines

File: source/module_basis/module_pw/module_fft/fft_cpu.cpp (hunk 14 above)
Comment (A-006) [reply source/module_basis/module_pw/module_fft/fft_cpu.cpp]: The problem has already been resolved.

File: source/module_esolver/esolver_fp.cpp (hunk 16 above)
Comment (A-006) [reply source/module_esolver/esolver_fp.cpp]: The problem has already been resolved.

File: tests/integrate/102_PW_CG_float/README
Comment (A-006) [reply tests/integrate/102_PW_CG_float/README:1]: The README has already been resolved.

File: tests/integrate/102_PW_CG_GPU_float/README
Comment (A-006) [reply tests/integrate/102_PW_CG_GPU_float/README:1]: The README has already been changed.

File: tests/integrate/102_PW_BPCG_GPU_float/README (hunk 17 above)
Comment (A-006) [reply tests/integrate/102_PW_BPCG_GPU_float/README]: The README has already been changed.

File: source/module_base/test/math_chebyshev_test.cpp (hunk 13 above)
Comment (A-006) [reply source/module_base/test/math_chebyshev_test.cpp:625]: A new MPI test case, MathChebyshevTest, has been added to the gtest framework.

File: source/module_basis/module_pw/module_fft/fft_cpu.cpp (hunk 15 above)
Comment (A-006) [reply source/module_basis/module_pw/module_fft/fft_cpu.cpp:352]: In the Si and AsCa systems, using `parallel omp for` achieves half the performance speedup compared to MPI. Other systems have not been tested yet; I will conduct more tests on additional systems and provide a performance report.

File: source/module_basis/module_pw/pw_gatherscatter.h [hunk 18]
```diff
@@ -98,7 +98,7 @@ void PW_Basis::gatherp_scatters(std::complex<T>* in, std::complex<T>* out) const
 template <typename T>
 void PW_Basis::gathers_scatterp(std::complex<T>* in, std::complex<T>* out) const
 {
-    //ModuleBase::timer::tick(this->classname, "gathers_scatterp");
+    ModuleBase::timer::tick(this->classname, "gathers_scatterp");
```
Comment (mohanchen) [inline source/module_basis/module_pw/pw_gatherscatter.h]: will it cost a lot of counting numbers?

File: source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt [hunk 19]
```diff
@@ -2,6 +2,7 @@ remove_definitions(-D__DEEPKS)
 remove_definitions(-D__CUDA)
 remove_definitions(-D__ROCM)
 remove_definitions(-D__EXX)
+remove_definitions(-DUSE_PAW)
```
Comment (mohanchen) [inline source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt:5]: we will delete PAW

File: tests/integrate/102_PW_CG/README
Comment (mohanchen) [inline tests/integrate/102_PW_CG/README:1]: don't write README in this way, need to discuss

File: source/module_lr/esolver_lrtd_lcao.cpp [hunk 20]
```diff
@@ -257,7 +257,11 @@ LR::ESolver_LR<T, TR>::ESolver_LR(ModuleESolver::ESolver_KS_LCAO<T, TR>&& ks_sol
     this->gint_->reset_DMRGint(1);
 
     // move pw basis
-    delete this->pw_rho;    // newed in ESolver_FP::ESolver_FP
+    if (this->pw_rho_flag)
```
Comment (mohanchen) [inline source/module_lr/esolver_lrtd_lcao.cpp:260]: need to discuss

File: source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt (hunk 6 above)
Comment (mohanchen) [inline source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt:32]: what's the aim of this test?

File: source/module_esolver/esolver_fp.cpp [hunk 21]
```diff
@@ -23,45 +23,60 @@ namespace ModuleESolver
...
+}
+
+ESolver_FP::~ESolver_FP()
+{
+    if (pw_rho_flag == true)
+    {
+        delete this->pw_rho;
+        this->pw_rho_flag = false;
+    }
+    if ( PARAM.globalv.double_grid)
```
Comment (mohanchen) [inline source/module_esolver/esolver_fp.cpp]: extra blank found

File: source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt (hunk 6 above)
Comment (A-006) [reply source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt:32]: The error with the float type originated from the structure_factor function, which did not have a test for float inputs. We have now added the test to prevent this issue from occurring again.

File: source/module_esolver/esolver_fp.cpp (hunk 21 above)
Comment (A-006) [reply source/module_esolver/esolver_fp.cpp]: The blank has been deleted.

File: source/module_basis/module_pw/pw_gatherscatter.h (hunk 18 above)
Comment (A-006) [reply source/module_basis/module_pw/pw_gatherscatter.h]: The time ticker has been deleted.

File: source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt (hunk 19 above)
Comment (A-006) [reply source/module_hamilt_pw/hamilt_pwdft/test/CMakeLists.txt:5]: The command has been deleted.

File: tests/integrate/102_PW_CG/README
Comment (A-006) [reply tests/integrate/102_PW_CG/README:1]: The README has been rewritten.

**Review by mohanchen — APPROVED** [review]
