### PR TITLE
Symmetry debug when input structure is not the best symmetric system

### LINKED ISSUE #481: k-point symmetry affects final energy in simple monoclinic lattice in both pw and LCAO base
## Describe the Bug
k-point symmetry affects final energy in simple monoclinic lattice in both pw and LCAO base 

## To Reproduce
diff 812_PW_LT_sm_symmetry_0/result.ref 812_PW_LT_sm_symmetry_1/result.ref
diff 826_NO_LT_sm_symmetry_0/result.ref 826_NO_LT_sm_symmetry_1/result.ref 
[simple_monoclinic_bug.tar.gz](https://github.com/deepmodeling/abacus-develop/files/7608001/simple_monoclinic_bug.tar.gz)

### PR DESCRIPTION
**Pull request by dyzheng**

### CODE REVIEW

File: source/module_symmetry/symmetry.cpp [hunk 1]
```diff
@@ -156,21 +156,29 @@ void Symmetry::analy_sys(const UnitCell_pseudo &ucell, std::ofstream &ofs_runnin
...
-    this->setgroup(this->symop, this->nop, this->ibrav);
-    //now select all symmetry operations which reproduce the lattice
-    //to find those symmetry operations which reproduce the entire crystal
-    this->getgroup(this->nrot, this->nrotk, ofs_running);
-    // find the name of point group
-    this->pointgroup(this->nrot, this->pgnumber, this->pgname, this->gmatrix, ofs_running);
-    ModuleBase::GlobalFunc::OUT(ofs_running,"POINT GROUP", this->pgname);
-    //write();
+	test_brav = true; // output the real ibrav and point group
+	ModuleBase::GlobalFunc::OUT(ofs_running,"ibrav",real_brav);
```
Comment (wenfei-li) [inline source/module_symmetry/symmetry.cpp:166]: it might be better if we notify the user that their input lattice type is not the optimal one
