### PR TITLE
Fix: fix the bug when reuse the numerical_basis class instance

### LINKED ISSUE #3605: Bug: present `Numerical_Basis` memory management is risky
### Describe the Code Quality Issue
Present support of multiple `bessel_nao_rcut` values may trigger a bug that output orb_matrix* files are broken but unawared by ABACUS. It is because
```c++
        if (winput::out_spillage <= 2)
        {
            Numerical_Basis numerical_basis;
            if(INPUT.bessel_nao_rcuts.size() == 1)
            {
                numerical_basis.output_overlap(this->psi[0], this->sf, this->kv, this->pw_wfc);
            }
            else
            {
                for(int i = 0; i < INPUT.bessel_nao_rcuts.size(); i++)
                {
                    if(GlobalV::MY_RANK == 0) {std::cout << "update value: bessel_nao_rcut <- " << std::fixed << INPUT.bessel_nao_rcuts[i] << " a.u." << std::endl;}
                    INPUT.bessel_nao_rcut = INPUT.bessel_nao_rcuts[i];
                    numerical_basis.output_overlap(this->psi[0], this->sf, this->kv, this->pw_wfc);
                    std::string old_fname_header = winput::spillage_outdir + "/" + "orb_matrix.";
                    std::string new_fname_header = winput::spillage_outdir + "/" + "orb_matrix_rcut" + std::to_string(int(INPUT.bessel_nao_rcut)) + "deriv";
                    for(int derivative_order = 0; derivative_order <= 1; derivative_order++)
                    {
                        // rename generated files
                        std::string old_fname = old_fname_header + std::to_string(derivative_order) + ".dat";
                        std::string new_fname = new_fname_header + std::to_string(derivative_order) + ".dat";
                        std::rename(old_fname.c_str(), new_fname.c_str());
                    }
                }
            }
            ModuleBase::GlobalFunc::DONE(GlobalV::ofs_running, "BASIS OVERLAP (Q and S) GENERATION.");
        }
```
if change to 
```c++
        if (winput::out_spillage <= 2)
        {
            if(INPUT.bessel_nao_rcuts.size() == 1)
            {
                Numerical_Basis numerical_basis;
                numerical_basis.output_overlap(this->psi[0], this->sf, this->kv, this->pw_wfc);
            }
            else
            {
                for(int i = 0; i < INPUT.bessel_nao_rcuts.size(); i++)
                {
                    if(GlobalV::MY_RANK == 0) {std::cout << "update value: bessel_nao_rcut <- " << std::fixed << INPUT.bessel_nao_rcuts[i] << " a.u." << std::endl;}
                    INPUT.bessel_nao_rcut = INPUT.bessel_nao_rcuts[i];
                    Numerical_Basis numerical_basis;
                    numerical_basis.output_overlap(this->psi[0], this->sf, this->kv, this->pw_wfc);
                    std::string old_fname_header = winput::spillage_outdir + "/" + "orb_matrix.";
                    // well actually the bessel_nao_rcut is not necessary to be integer, present way is because of historically reason.
                    std::string new_fname_header = winput::spillage_outdir + "/" + "orb_matrix_rcut" + std::to_string(int(INPUT.bessel_nao_rcut)) + "deriv";
                    for(int derivative_order = 0; derivative_order <= 1; derivative_order++)
                    {
                        // rename generated files
                        std::string old_fname = old_fname_header + std::to_string(derivative_order) + ".dat";
                        std::string new_fname = new_fname_header + std::to_string(derivative_order) + ".dat";
                        std::rename(old_fname.c_str(), new_fname.c_str());
                    }
                }
            }
            ModuleBase::GlobalFunc::DONE(GlobalV::ofs_running, "BASIS OVERLAP (Q and S) GENERATION.");
        }
```
then orb_matrix* can have complete information. But it implies the memory management inside `Numerical_Basis` is not-well-designed, seems it highly relies on auto-destroy instead of being with a mechanism to refresh/reset its data if want a second use, which means, therefore the management of data and calculation of data are within the same class, and this class is not designed clearly in aspect whether it SHOULD BE a singleton or common object for its instance.

During refactor of orbital generation suites, I also find there may be only one parameter in INPUTw is needed, say the `out_spillage`, although it seems the orbital generation code can also be used to "wannierize" selected planewave wavefunction, but the INPUTw related functionalities are in state of nobody-maintained.
Have plan to merge settings in INPUTw to INPUT.

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

### PR DESCRIPTION
**Pull request by kirk0830**
### N.B.
This PR is just an opening of refactor of old `Numerical_Basis` class. A framework of xml library will be beneficial for making several classes in ABACUS lighter and clean.

### Reminder
- [x] Have you linked an issue with this pull request?
- [x] Have you noticed possible changes of behavior below or in the linked issue?
- [x] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #3605 

### What's changed?
- see issue #3605 

### Any changes of core modules? (ignore if not applicable)
- change esolver_ks_pw the numerical atomic orbital generation, the life span of numerical_basis instance.

### CODE REVIEW

File: source/module_io/to_xml.h [hunk 1]
```diff
@@ -0,0 +1,29 @@
+/*
+To print any kind of information to an XML file
```
Comment (dyzheng) [inline source/module_io/to_xml.h]: Sorry, I don't understand the usage of this file?

Comment (kirk0830) [reply source/module_io/to_xml.h]: Currently in ABACUS there are many output files organized in the way like xml but the root tag is absent.
The present xml-like format will only be quite slightly benificial for organizing human-readable information but for large files, few people will read them, instead, machine/program will be the ultimate one read them and do postprocessing. However, due to ill-defined file structure, the absent root tag will cause failure of xml file parse (like xml library of Python), which means the xml-like format will not be beneficial for both human and program!
Therefore, I want to add this small library uniformly control and standardize the xml-like output, so that parsing some output will be easier.
But I just create this file here and not complete the implementation yet...

Comment (kirk0830) [reply source/module_io/to_xml.h]: I have moved this file to another branch~

File: source/module_io/numerical_basis.cpp [hunk 2]
```diff
@@ -139,12 +139,11 @@ void Numerical_Basis::output_overlap(const psi::Psi<std::complex<double>>& psi,
         }
         Parallel_Reduce::reduce_pool(overlap_V.c, overlap_V.nr * overlap_V.nc);		// Peize Lin add 2020.04.23
     #endif
+        if(ofs.good()) this->output_info(ofs, bessel_basis, kv); else assert(false);
```
Comment (dyzheng) [inline source/module_io/numerical_basis.cpp]: "assert" will stpp the program without printing any useful information, why not use "WARNING_QUIT("...","...")" ?

File: source/module_io/numerical_basis.cpp [hunk 3]
```diff
@@ -694,8 +694,9 @@ void Numerical_Basis::output_overlap_Q(std::ofstream& ofs,
             const int dim = Qtmp.getSize();
             for (int i=0; i<dim; i++)
             {
-                if ( count%4==0 ) ofs << "\n";
+                if ( count%4==0 ) ofs << std::endl;
                 ofs << " " << Qtmp.ptr[i].real() << " " << Qtmp.ptr[i].imag();
+                ofs.flush();
```
Comment (dyzheng) [inline source/module_io/numerical_basis.cpp]: Will high frequency flushing slow down the efficiency of this function?

File: source/module_io/numerical_basis.cpp (hunk 2 above)
Comment (kirk0830) [reply source/module_io/numerical_basis.cpp]: Thanks for pointing out this, please see the modified code

File: source/module_io/numerical_basis.cpp (hunk 3 above)
Comment (kirk0830) [reply source/module_io/numerical_basis.cpp]: I think so, but I notice after every four numbers are written, there will be a flush by endl, I have deleted flush here

**Review by dyzheng — APPROVED** [review]
LGTM
