### PR TITLE
Fix energy jumps occur in rt-TDDFT calculations

### LINKED ISSUE #6778: Energy jumps occur in rt-TDDFT calculations.
### Describe the bug

If ions are allowed to move, rt-TDDFT calculations exhibit energy jumps at certain time points. The cause is matrix discontinuity due to ions traversing periodic boundaries. 

Image

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by ESROAMER**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #6778 

### What's changed?
To fix the discontinuity caused by ions crossing boundaries, an additional phase must be added to the relevant matrix each time a crossing occurs. Here are the results after applying the fix.
Comparison_plot

### Any changes of core modules? (ignore if not applicable)
An additional member variable `boundary_shift` was added to the class `Atom`  to track ion boundary crossings.

### CODE REVIEW

File: source/source_cell/atom_spec.cpp [hunk 1]
```diff
@@ -101,6 +101,7 @@ void Atom::bcast_atom()
             this->tau.resize(na, ModuleBase::Vector3<double>(0, 0, 0));
             this->dis.resize(na, ModuleBase::Vector3<double>(0, 0, 0));
             this->taud.resize(na, ModuleBase::Vector3<double>(0, 0, 0));
+            this->boundary_shift.resize(na, ModuleBase::Vector3<int>(0, 0, 0));
```
Comment (mohanchen) [inline source/source_cell/atom_spec.cpp:104]: is it better to use size_t instead of int? (in case the number of atoms is huge)

File: source/source_lcao/module_rt/boundary_fix.cpp [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+namespace module_rt{
+
+void reset_matrix_boundary(const UnitCell& ucell,
+                           const K_Vectors& kv,
+                           const Parallel_Orbitals* pv,
+                           ct::Tensor& hk_last,
+                           ct::Tensor& sk_last,
+                           psi::Psi<std::complex<double>>* psi_last,
+                           const int len_hs)
+{
```
Comment (mohanchen) [inline source/source_lcao/module_rt/boundary_fix.cpp:15]: it wold be better to add a 'title' and a 'timer' for this function

File: source/source_lcao/module_rt/boundary_fix.cpp [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+    return;
+}
+
+void boundary_shift_mat(const std::complex<double>& phase,
+                        std::complex<double>* matk,
+                        const Parallel_Orbitals* pv,
+                        const int iat)
+{
+    const std::complex<double> phase_conj = std::conj(phase);
+    int row0 = pv->atom_begin_row[iat];
```
Comment (mohanchen) [inline source/source_lcao/module_rt/boundary_fix.cpp]: better to use size_t instead of int

**Comment by mohanchen** [comment]
Nice job!

File: source/source_cell/atom_spec.cpp (hunk 1 above)
Comment (ESROAMER) [reply source/source_cell/atom_spec.cpp:104]: > is it better to use size_t instead of int? (in case the number of atoms is huge)

size_t should not be used here because this int value does not represent the atom index. Instead, it indicates the direction and number of times an atom has crossed the periodic cell boundary. Its possible values are strictly `-1`, `0`, or `1` (crossing two cells at once triggers a warning quit). Therefore,  the sign instead of magnitude is important.

File: source/source_lcao/module_rt/boundary_fix.cpp (hunk 2 above)
Comment (ESROAMER) [reply source/source_lcao/module_rt/boundary_fix.cpp:15]: Okay, I'll add it.

File: source/source_lcao/module_rt/boundary_fix.cpp (hunk 3 above)
Comment (ESROAMER) [reply source/source_lcao/module_rt/boundary_fix.cpp]: This one would be changed.

**Review by AsTonyshment — APPROVED** [review]
👍

**Review by mohanchen — APPROVED** [review]
LGTM
