### PR TITLE
Fix GPU single precision energy error in dav_subspace solver

### LINKED ISSUE #6867: Inconsistent result of GPU/CPU dav_subspace
### Describe the bug

`dav_subspace` GPU gives different total energy than CPU.

CPU
```
!FINAL_ETOT_IS -4869.7470518614691173 eV
```

GPU
```
!FINAL_ETOT_IS -4858.3154362329169089 eV
```

### Expected behavior

They should give the same results for CPU/GPU version.

### To Reproduce

run `tests/11_PW_GPU/003_PW_DA_GPU` with `ks_solver`=`dav_subspace`, and `device`=`gpu`.

### Environment

ABACUS develop (v3.9.0.22) commit ed0b428

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by zhubonan**
## Summary
- Restore `d_precondition` host-to-device sync that was commented out in #5199 (this caused uninitialized GPU memory to be used as the preconditioner)
- Fix cuBLAS gemv calls using `incx` instead of `incy` for Y parameter
- Fix gemv_batched using `incy` instead of `incx` for x parameter
- Replace some gemm operations with gemv when the number of columns is one. 

## Root Cause for the dav_subspace solver problem

The `syncmem_var_h2d_op()` call for `d_precondition` was commented out in commit a5c35d93f (#5199), causing the GPU preconditioner array to contain uninitialized memory. This led to incorrect preconditioning in the Davidson subspace iterations, resulting in wrong energies for GPU single precision calculations (~0.027 eV error).

Note: The problem may not always be reproducible since uninitialized memory may contain random data.

## Reason for replacing gemm with gemv

I found the code crashes with GPU double precision in dav and dav_supspace. Not a problem with the CG solver. The crash occurs at the gemm call with `notconv=1`.

## Test Results
Tested with `examples/02_scf/pw_Si2` on CUDA 12.8 with NVIDIA GeForce RTX 5090:

| Configuration | Energy (eV) | Status |
|--------------|-------------|--------|
| cpu_single | -215.505698 | ✓ |
| cpu_double | -215.505698 | ✓ |
| gpu_single | -215.505686 | ✓ (was -215.4787) |
| gpu_double | -215.505698 | ✓ |

Fixes #6867

### CODE REVIEW

**Comment by dyzheng** [comment]
LGTM, Thanks for this fix, I will check the result on ROCM.

**Review by dyzheng — APPROVED** [review]

**Review by Critsium-xy — APPROVED** [review]

File: source/source_hsolver/diago_david.cpp [hunk 1]
```diff
@@ -411,20 +429,37 @@ void DiagoDavid<T, Device>::cal_grad(const HPsiFunc& hpsi_func,
...
-                                     spsi,                // A
-                                     dim,                 // LDA: if(N) max(1,m) if(T) max(1,k)
-                                     vc_ev_vector,        // B
-                                     nbase,               // LDB: if(N) max(1,k) if(T) max(1,n)
-                                     this->one,           // belta
-                                     basis + dim * nbase, // C dim * notconv
-                                     dim                  // LDC: if(N) max(1, m)
-    );
+    if (notconv == 1){
+        //Use gemv for vector case to avoid potential bug using gemm call with n=1
```
Comment (Cstandardlib) [inline source/source_hsolver/diago_david.cpp:433]: I'm just curious about what potential bugs gemm might occur when n=1 😮 I didn't realize that before

File: source/source_hsolver/diago_dav_subspace.cpp [hunk 2]
```diff
@@ -313,6 +315,28 @@ void Diago_DavSubspace<T, Device>::cal_grad(const HPsiFunc& hpsi_func,
                          this->zero,
                          psi_iter + (nbase) * this->dim,
                          this->dim);
+    } else
+    {
+
+#ifdef __DSP
+    ModuleBase::gemv_op_mt<T, Device>()
```
Comment (Cstandardlib) [inline source/source_hsolver/diago_dav_subspace.cpp:322]: We have not implemented `gemv_op_mt` on DSP yet, and I will add this part later in a next PR

**Review by Cstandardlib — APPROVED** [review]
LGTM! Thanks for the fix.
Now that only `gemm_op_mt` is supported on DSP device, I will add `gemv_op_mt` implementation next. This is only used on DSP acceleration clusters and won't block the PR from being merged.​

**Comment by Cstandardlib** [comment]
And there are some code conflicts that need to be resolved, caused by #6936, which unify the CUBLAS check macro(cublasErrcheck->CHECK_CUBLAS).

File: source/source_hsolver/diago_david.cpp (hunk 1 above)
Comment (zhubonan) [reply source/source_hsolver/diago_david.cpp:433]: It just ended up as segmentation fault. Not sure why but maybe cublas' gemm does some certain kernel optimizations result in reading beyond the boundary. It is likely to be vendor/library/hardware specific. 
Using gemv should be more robust as it is designed for matrix-vector product.

File: source/source_hsolver/diago_dav_subspace.cpp (hunk 2 above)
Comment (zhubonan) [reply source/source_hsolver/diago_dav_subspace.cpp:322]: OK. Do you suggest leaving it as it is for now or I can revert to `gemm_op_mt`?

File: source/source_hsolver/diago_david.cpp (hunk 1 above)
Comment (Cstandardlib) [reply source/source_hsolver/diago_david.cpp:433]: Got it, thanks for the explanation! Very helpful to understand why gemv is safer here.

File: source/source_hsolver/diago_dav_subspace.cpp (hunk 2 above)
Comment (Cstandardlib) [reply source/source_hsolver/diago_dav_subspace.cpp:322]: It's OK to leave `gemv_op_mt` here as it will only compile when `USE_DSP` is ON, and will cause no side effects on general CPU/GPU/DCU hardwares or CI/CD.
