### PR TITLE
Fix the incorrect calculation of partial charge for multi-k-points under both PW and LCAO when symmetry is turned on

### LINKED ISSUE #4740: Bug: Incorrect calculation of partial charge for multi-k-points under both PW and LCAO when symmetry is turned on
### Describe the bug

I am currently writing a tutorial on how to calculate and visualize band-decomposed (partial) charge density. However, when I attempt to calculate and draw the `.cube` charge file, the results from PW and LCAO basis set appear to be inconsistent. Attached are some benchmark results using 2D graphene with a 2×2×2 k-points sampling.

BAND1 (VASP)
image
BAND1 (ABACUS, LCAO)
image
BAND1 (ABACUS, PW)
image

It appears that under the PW basis set, only the charge of certain specific k-points is taken into account. The observed pattern matches the result of the k-point (0.5, 0.5, 0.5) (in terms of k-points sampling using DIRECT coordinates in output file `kpoints`):

BAND1 K(0.5, 0.5, 0.5) (VASP)
image
BAND1 K(0.5, 0.5, 0.5) (ABACUS, LCAO)
image

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by AsTonyshment**
### Linked Issue
Fix #4740 

### What's changed?
- Added a new `begin` function in `symmetry_rho.cpp` that can be initialized without using the `Charge` class. The original `begin` function will be removed to eliminate the dependency of `Symmetry_rho` on `Charge`, but this change will be addressed in a separate PR (not this one).
- Symmetrized the charge density in `istate_charge.cpp`, ensuring that the band-decomposed charge density calculation remains correct under multi-k-points in the LCAO basis when symmetry is enabled.
- Symmetrized the charge density in `esolver_ks_pw.cpp`, ensuring that the band-decomposed charge density calculation remains correct under multi-k-points in the PW basis when symmetry is enabled.

### Benchmark
_**All the results below were obtained with `symmetry = 1`.**_ The benchmark system used is a monolayer of graphene. Testing with `nspin = 2` was also conducted, and it worked correctly.

BAND1 (VASP)
image
BAND1 (ABACUS, LCAO)
image
BAND1 (ABACUS, PW)
image

### CODE REVIEW

File: source/module_elecstate/module_charge/symmetry_rho.cpp [hunk 1]
```diff
@@ -17,96 +16,142 @@ void Symmetry_rho::begin(const int& spin_now,
...
     // if(symm.nrot==symm.nrotk) //pure point-group, do rho_symm in real space
     // {
     // 	psymm(CHR.rho[spin_now], rho_basis, Pgrid, symm);
-    // 	if(XC_Functional::get_func_type() == 3 || XC_Functional::get_func_type() == 5) psymm(CHR.kin_r[spin_now], rho_basis,Pgrid,symm);
+    // 	if(XC_Functional::get_func_type() == 3 || XC_Functional::get_func_type() == 5) psymm(CHR.kin_r[spin_now],
+    // rho_basis,Pgrid,symm);
     // }
     // else	//space group, do rho_symm in reciprocal space
-	{
-		rho_basis->real2recip(CHR.rho[spin_now], CHR.rhog[spin_now]);
```
Comment (mohanchen) [inline source/module_elecstate/module_charge/symmetry_rho.cpp:31]: what is CHR here, a member of symmetry?

File: source/module_elecstate/module_charge/symmetry_rho.cpp [hunk 2]
```diff
@@ -17,96 +16,142 @@ void Symmetry_rho::begin(const int& spin_now,
...
-			rho_basis->real2recip(CHR.kin_r[spin_now], kin_g);
-			psymmg(kin_g,  rho_basis,Pgrid,symm);
-			rho_basis->recip2real(kin_g, CHR.kin_r[spin_now]);
-			delete[] kin_g;
-		}	
-	}
-	return;
+        if (XC_Functional::get_func_type() == 3 || XC_Functional::get_func_type() == 5)
+        {
+            std::complex<double>* kin_g = new std::complex<double>[CHR.ngmc];
```
Comment (mohanchen) [inline source/module_elecstate/module_charge/symmetry_rho.cpp]: could you use std::vector instead of new and delete?

File: source/module_elecstate/module_charge/symmetry_rho.cpp [hunk 3]
```diff
@@ -17,96 +16,142 @@ void Symmetry_rho::begin(const int& spin_now,
...
-	{
-		rhotot = new double[rho_basis->nxyz];
-		ModuleBase::GlobalFunc::ZEROS(rhotot, rho_basis->nxyz);
-	}
-	Pgrid.reduce_to_fullrho(rhotot, rho_part);
+    // (1) reduce all rho from the first pool.
+    double* rhotot;
+    if (GlobalV::MY_RANK == 0)
+    {
+        rhotot = new double[rho_basis->nxyz];
```
Comment (mohanchen) [inline source/module_elecstate/module_charge/symmetry_rho.cpp]: could you use std::vector instead of new and delete?

File: source/module_elecstate/module_charge/symmetry_rho.cpp (hunk 1 above)
Comment (AsTonyshment) [reply source/module_elecstate/module_charge/symmetry_rho.cpp:31]: No, this refers to the `Charge` class. I have retained the old interface in this PR for compatibility and added a new `begin` function that does not require `Charge`. Completely removing `Charge` from `Symmetry_rho` will be addressed in a separate PR linked to a distinct issue.

File: source/module_elecstate/module_charge/symmetry_rho.cpp [hunk 4]
```diff
@@ -17,96 +16,137 @@ void Symmetry_rho::begin(const int& spin_now,
...
+}
+    // both parallel and serial
+    // if(symm.nrot==symm.nrotk) //pure point-group, do rho_symm in real space
+    // {
+    // 	psymm(CHR.rho[spin_now], rho_basis, Pgrid, symm);
+    // 	if(XC_Functional::get_func_type() == 3 || XC_Functional::get_func_type() == 5) psymm(CHR.kin_r[spin_now],
+    // rho_basis,Pgrid,symm);
+    // }
+    // else	//space group, do rho_symm in reciprocal space
+    {
```
Comment (mohanchen) [inline source/module_elecstate/module_charge/symmetry_rho.cpp:32]: what is this '{' used for?

File: source/module_elecstate/module_charge/symmetry_rho.cpp [hunk 5]
```diff
@@ -17,96 +16,137 @@ void Symmetry_rho::begin(const int& spin_now,
...
+
+        if (XC_Functional::get_func_type() == 3 || XC_Functional::get_func_type() == 5)
+        {
+            // Use std::vector to manage kin_g instead of raw pointer
+            std::vector<std::complex<double>> kin_g(CHR.ngmc);
+            rho_basis->real2recip(CHR.kin_r[spin_now], kin_g.data());
+            psymmg(kin_g.data(), rho_basis, Pgrid, symm);
+            rho_basis->recip2real(kin_g.data(), CHR.kin_r[spin_now]);
+        }
+    }
```
Comment (mohanchen) [inline source/module_elecstate/module_charge/symmetry_rho.cpp:45]: what is this '}' used for?

File: source/module_io/istate_envelope.cpp
Comment (mohanchen) [inline source/module_io/istate_envelope.cpp:1]: Do you think it would be better to change the file name from "istate_envelope" to "get_wf"?

File: source/module_io/istate_charge.h
Comment (mohanchen) [inline source/module_io/istate_charge.h:1]: Do you think it would be better to change the file name from "istate_charge" to "get_pchg"?

File: source/module_esolver/esolver_ks_pw.cpp [hunk 6]
```diff
@@ -816,14 +817,45 @@ void ESolver_KS_PW<T, Device>::after_scf(const int istep) {
...
                 }
             }
 
+            // Symmetrize the charge density, otherwise the results are incorrect if the symmetry is on
+            std::cout << " Symmetrizing band-decomposed charge density..." << std::endl;
+            Symmetry_rho srho;
+            for (int is = 0; is < GlobalV::NSPIN; is++)
+            {
+                // Create pointers to the data structures
+                double** rho_save_pointers = new double*[GlobalV::NSPIN];
```
Comment (mohanchen) [inline source/module_esolver/esolver_ks_pw.cpp]: it would be better to use std::vector than new and delete

File: source/module_esolver/esolver_ks_pw.cpp [hunk 7]
```diff
@@ -816,14 +817,45 @@ void ESolver_KS_PW<T, Device>::after_scf(const int istep) {
...
+                std::complex<double>** rhog = new std::complex<double>*[GlobalV::NSPIN];
```
Comment (mohanchen) [inline source/module_esolver/esolver_ks_pw.cpp]: std::vector to replace new and delete

File: source/module_esolver/esolver_ks_pw.cpp (hunk 6 above)
Comment (AsTonyshment) [reply source/module_esolver/esolver_ks_pw.cpp]: Done.

File: source/module_esolver/esolver_ks_pw.cpp (hunk 7 above)
Comment (AsTonyshment) [reply source/module_esolver/esolver_ks_pw.cpp]: Done.

File: source/module_io/istate_envelope.cpp
Comment (AsTonyshment) [reply source/module_io/istate_envelope.cpp:1]: I think you have a point. The renaming has been completed.

File: source/module_io/istate_charge.h
Comment (AsTonyshment) [reply source/module_io/istate_charge.h:1]: I think you have a point. The renaming has been completed.

File: source/module_elecstate/module_charge/symmetry_rho.cpp (hunk 4 above)
Comment (AsTonyshment) [reply source/module_elecstate/module_charge/symmetry_rho.cpp:32]: The extra pair of braces was originally added to enclose a block of code that has since been commented out by @maki49 (in PR[#3081](https://github.com/deepmodeling/abacus-develop/pull/3081), at least based on the information from the git log), as you can see above. I decided to keep the original structure intact because I'm unsure if this code will be re-enabled in the future.

**Review by mohanchen — APPROVED** [review]
