### PR TITLE
Fix: Solve mpi bug for DeePKS.

### LINKED ISSUE #5874: Bug: Error when using MPI version DeePKS.
### Describe the bug

When using mpirun for DeePKS scf, it will exit abnormally. The bug is introduced in #5766.

I have found that the source of the problem is inter-process data access, and the source is the creation and use of the `AtomPair` class in `HContainer`. `AtomPair` supports the creation of objects if the process contains basis of atomic pairs, but the basis of one of the atoms in DeePKS are replaced so that the original `Parallel_Orbitals` object does not correctly reflect the actual tracks used, resulting in incorrect calculations at creation and reference time.

I will create a new `Parallel_Orbitals` class for DeePKS to fix this bug.

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by ErjieWu**
### Linked Issue
Fix #5874

### What's changed?
- Avoid using Parallel_Orbitals to create HContainer using for saving phialpha in DeePKS.
- Add some timer ticks for calculations in DeePKS.

### CODE REVIEW

File: source/module_hamilt_lcao/module_deepks/deepks_basic.cpp [hunk 1]
```diff
@@ -64,6 +69,7 @@ void DeePKS_domain::load_model(const std::string& model_file, torch::jit::script
         std::cerr << "error loading the model" << std::endl;
         return;
```
Comment (mohanchen) [inline source/module_hamilt_lcao/module_deepks/deepks_basic.cpp:71]: add timer::tick before return?

**Review by mohanchen — APPROVED** [review]
