### PR TITLE
Test: supplementary use of Memory::record to record memory

### LINKED ISSUE #3657: Large memory costs for LCAO calculations (Fe with 32 atoms)
### Describe the bug

Job kill by signal 9 in two Fe systems
Bohrium links:
Fe32: https://bohrium.dp.tech/jobs/detail/11340467
Fe33: https://bohrium.dp.tech/jobs/detail/11340457

### Expected behavior

no error

### To Reproduce

[test_tzdp.tar.gz](https://github.com/deepmodeling/abacus-develop/files/14429838/test_tzdp.tar.gz)

One Fe32 system, one Fe33 system.

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [x] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by Religious-J**
### Reminder
- [x] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [x] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue 
#3657 Milestone 1

### Unit Tests and/or Case Tests for my changes
No

### What's changed?
In response to issue #3657, the peak memory application recorded using `ModuleBase::Memory::record` is quite different from that recorded using `ModuleBase::TITLE`. Therefore, after preliminary statistical analysis of memory application during program running, supplement the key functions of missing records in `ModuleBase::Memory::record` method. (such as `Symmetry::rhog_symmetry()` , `XC_Functional::gradcorr()`, `Charge::allocate()` ...)

### CODE REVIEW

**Review by caic99 — APPROVED** [review]

File: source/module_base/clebsch_gordan_coeff.cpp [hunk 1]
```diff
@@ -30,6 +31,7 @@ void Clebsch_Gordan::clebsch_gordan(const int& lli,
     ModuleBase::matrix ylm(llx, llx);
     ModuleBase::matrix mly(llx, llx);
 
+    ModuleBase::Memory::record("Clebsch_Gordan::matrix",sizeof(double)*llx*llx*2+sizeof(ModuleBase::Vector3<double>)*llx);
```
Comment (dyzheng) [inline source/module_base/clebsch_gordan_coeff.cpp]: what size will `llx` be in your test?
Only significant should be recorded.

File: source/module_base/module_container/ATen/core/tensor_buffer.cpp [hunk 2]
```diff
@@ -22,6 +23,7 @@ TensorBuffer::TensorBuffer(base::core::Allocator* alloc, size_t size) {
     alloc_ = alloc; 
     if (size > 0) {
         data_ = alloc_->allocate(size);
+        ModuleBase::Memory::record("TensorBuffer::data_",sizeof(size_t)*size);
```
Comment (dyzheng) [inline source/module_base/module_container/ATen/core/tensor_buffer.cpp]: `Tensor` is a container, it will used by developers for different purpose, the memory should be recorded by key word : `TensorBuffer::data_`.
I don't agree to record memory here, you should find the actual instantiated variables.

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 3]
```diff
@@ -51,6 +53,7 @@ void Symmetry::analy_sys(const Lattice& lat, const Statistics& st, Atom* atoms,
     rotpos = new double[3*nat];
 	ModuleBase::GlobalFunc::ZEROS(newpos, 3*nat);
     ModuleBase::GlobalFunc::ZEROS(rotpos, 3*nat);
+    ModuleBase::Memory::record("Symmetry::analy_sys",sizeof(int)*(ntype*2+nat+2)+sizeof(double)*(nat*6));
```
Comment (dyzheng) [inline source/module_cell/module_symmetry/symmetry.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 4]
```diff
@@ -1209,6 +1215,7 @@ void Symmetry::pricell(double* pos, const Atom* atoms)
 
     //sort ptrans:
     double* ptrans_array = new double[ntrans*3];
+    ModuleBase::Memory::record("Symmetry::ptrans_array",sizeof(double)*ntrans*3);
```
Comment (dyzheng) [inline source/module_cell/module_symmetry/symmetry.cpp:1217]: This looks like a small memory cost, what size in your test?

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 5]
```diff
@@ -1472,6 +1482,12 @@ void Symmetry::rhog_symmetry(std::complex<double> *rhogtot,
     int(*isymflag)[48] = new int[fftnx*fftny*fftnz][48];//which rotration operation the grid corresponds to
     int(*table_xyz)[48] = new int[fftnx * fftny * fftnz][48];// group information
     int* count_xyz = new int[fftnx * fftny * fftnz];// how many symmetry operations has been covered
+    // ModuleBase::Memory::record("Symmetry::rhog_symmetry",sizeof(int) *fftnx*fftny*fftnz*98);
+    ModuleBase::Memory::record("Symmetry::symflag",sizeof(int) *fftnx*fftny*fftnz);
+    ModuleBase::Memory::record("Symmetry::isymflag",sizeof(int) *fftnx*fftny*fftnz*48);
+    ModuleBase::Memory::record("Symmetry::table_xyz",sizeof(int) *fftnx*fftny*fftnz*48);
+    ModuleBase::Memory::record("Symmetry::count_xyz",sizeof(int) *fftnx*fftny*fftnz);
```
Comment (dyzheng) [inline source/module_cell/module_symmetry/symmetry.cpp]: I suggest to gather them into key word "Symmetry::rhog_symmetry"

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 6]
```diff
@@ -1483,6 +1499,7 @@ void Symmetry::rhog_symmetry(std::complex<double> *rhogtot,
 
     //map the gmatrix to inv
     int* invmap = new int[nrotk];
+    ModuleBase::Memory::record("Symmetry::invmap",sizeof(int)*nrotk);
```
Comment (dyzheng) [inline source/module_cell/module_symmetry/symmetry.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 7]
```diff
@@ -1601,6 +1618,7 @@ for (int g_index = 0; g_index < group_index; g_index++)
     int *ipw_record = new int[nrotk];
     int *ixyz_record = new int[nrotk];
     std::complex<double>* gphase_record = new std::complex<double> [nrotk];
+    ModuleBase::Memory::record("Symmetry::*_record",sizeof(int) *nrotk*2 + sizeof(std::complex<double>)*nrotk);
```
Comment (dyzheng) [inline source/module_cell/module_symmetry/symmetry.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_cell/module_symmetry/symmetry.cpp [hunk 8]
```diff
@@ -1740,6 +1758,7 @@ void Symmetry::symmetrize_vec3_nat(double* v)const   // pengfei 2016-12-20
     vtot = new double[nat * 3]; ModuleBase::GlobalFunc::ZEROS(vtot, nat * 3);
     n = new int[nat]; ModuleBase::GlobalFunc::ZEROS(n, nat);
 
+    ModuleBase::Memory::record("Symmetry::vtot&n",sizeof(int)*nat + sizeof(double)*nat*3);
```
Comment (dyzheng) [inline source/module_cell/module_symmetry/symmetry.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_cell/module_symmetry/symmetry_basic.cpp [hunk 9]
```diff
@@ -1111,6 +1112,7 @@ void Symmetry_Basic::atom_ordering_new(double *posi, const int natom, int *subin
 
 	double*  weighted_func = new double[natom];
 	
+	ModuleBase::Memory::record("Symmetry_Basic::tmp*",sizeof(double)*natom*4);
```
Comment (dyzheng) [inline source/module_cell/module_symmetry/symmetry_basic.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_hamilt_general/module_xc/xc_functional_gradcorr.cpp [hunk 10]
```diff
@@ -71,6 +73,7 @@ void XC_Functional::gradcorr(double &etxc, double &vtxc, ModuleBase::matrix &v,
 	// calculate the gradient of (rho_core+rho) in reciprocal space.
 	rhotmp1 = new double[rhopw->nrxx];
 	rhogsum1 = new std::complex<double>[rhopw->npw];
+	ModuleBase::Memory::record("XC_Functional::rho*",sizeof(std::complex<double>)*rhopw->npw+sizeof(double)*rhopw->nrxx);
```
Comment (dyzheng) [inline source/module_hamilt_general/module_xc/xc_functional_gradcorr.cpp]: Please calculate the total memory used in this function, and record it once with key word "XC_Functional::gradcorr".

File: source/module_hamilt_general/module_xc/xc_functional_vxc.cpp [hunk 11]
```diff
@@ -31,6 +33,7 @@ std::tuple<double,double,ModuleBase::matrix> XC_Functional::v_xc(
     double vtxc = 0.0;
     ModuleBase::matrix v(GlobalV::NSPIN, nrxx);
 
+    ModuleBase::Memory::record("xc_functional_vxc::matrix",sizeof(double)*GlobalV::NSPIN*nrxx);
```
Comment (dyzheng) [inline source/module_hamilt_general/module_xc/xc_functional_vxc.cpp]: In this function, the matrix `v` is the return variable, will be moved to the caller, please record it when it is called.

File: source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp [hunk 12]
```diff
@@ -443,6 +443,7 @@ void pseudopot_cell_vnl::getvnl(Device* ctx, const int& ik, std::complex<FPTYPE>
     resmem_var_op()(ctx, vkb1, nhm * npw, "VNL::vkb1");
 
     ModuleBase::Vector3<double>* _gk = new ModuleBase::Vector3<double>[npw];
+    ModuleBase::Memory::record("pseudopot_cell_vnl::getvnl",sizeof(ModuleBase::Vector3<double>)*npw+sizeof(int)*GlobalC::ucell.ntype*3);
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp]: Please only record `gk` here, the key word imply this memory covered all memory used in this function.

File: source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp [hunk 13]
```diff
@@ -569,6 +570,7 @@ void pseudopot_cell_vnl::init_vnl(UnitCell& cell, const ModulePW::PW_Basis* rho_
     this->dvan_so.zero_out(); // added by zhengdy-soc
     delete[] indv_ijkb0;
     this->indv_ijkb0 = new int[GlobalC::ucell.nat];
+    ModuleBase::Memory::record("pseudopot_cell_vnl::indv_ijkb0",sizeof(int)*GlobalC::ucell.nat);
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp [hunk 14]
```diff
@@ -820,6 +822,7 @@ void pseudopot_cell_vnl::init_vnl(UnitCell& cell, const ModulePW::PW_Basis* rho_
 
         double* jl = new double[kkbeta];
         double* aux = new double[kkbeta];
+        ModuleBase::Memory::record("pseudopot_cell_vnl::jl&aux",sizeof(double)*kkbeta*2);
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp [hunk 15]
```diff
@@ -897,6 +900,7 @@ void pseudopot_cell_vnl::compute_qrad(UnitCell& cell)
             double* aux = new double[kkbeta];
             double* besr = new double[kkbeta];
 
+            ModuleBase::Memory::record("pseudopot_cell_vnl::besr&aux",sizeof(double)*kkbeta*2);
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp [hunk 16]
```diff
@@ -1311,6 +1315,7 @@ void pseudopot_cell_vnl::init_vnl_alpha(void)          // pengfei Li 2018-3-23
 		double *jl = new double[kkbeta];
 		double *aux  = new double[kkbeta];
 
+        ModuleBase::Memory::record("pseudopot_cell_vnl::jl&aux_2",sizeof(double)*kkbeta*2);
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp [hunk 17]
```diff
@@ -1512,6 +1517,7 @@ void pseudopot_cell_vnl::newq(const ModuleBase::matrix& veff, const ModulePW::PW
     ModuleBase::YlmReal::Ylm_Real(lmaxq * lmaxq, npw, rho_basis->gcar, ylmk0);
 
     double* qnorm = new double[npw];
+    ModuleBase::Memory::record("pseudopot_cell_vnl::qnorm",sizeof(double)*npw);
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/VNL_in_pw.cpp]: Is `ylmk0` recorded?

File: source/module_hamilt_pw/hamilt_pwdft/forces.cpp [hunk 18]
```diff
@@ -46,6 +48,7 @@ void Forces<FPTYPE, Device>::cal_force(ModuleBase::matrix& force,
     ModuleBase::matrix forcescc(nat, 3);
     ModuleBase::matrix forcepaw(nat,3);
 
+    ModuleBase::Memory::record("Forces::matrix",sizeof(double)*nat*3*6);
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/forces.cpp]: This looks like a small memory cost, what size in your test?

File: source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp [hunk 19]
```diff
@@ -168,13 +168,15 @@ void diago_PAO_in_pw_k2(const int &ik,
     if (p_wf->init_wfc == "file")
     {
         ModuleBase::ComplexMatrix wfcatom(nbands, nbasis);
+        ModuleBase::Memory::record("wavefunc::wfcatom_3",nbands * nbasis * sizeof(std::complex<double>));
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp]: Key word should be `wavefunc::wfcatom`

File: source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp [hunk 20]
```diff
@@ -168,13 +168,15 @@ void diago_PAO_in_pw_k2(const int &ik,
...
         std::stringstream filename;
         filename << GlobalV::global_readin_dir << "WAVEFUNC" << ik + 1 << ".dat";
         bool result = ModuleIO::read_wfc_pw(filename.str(), wfc_basis, ik, p_wf->nkstot, wfcatom);
 
         if (result)
         {
             std::vector<std::complex<float>> s_wfcatom(nbands * nbasis);
+            ModuleBase::Memory::record("wavefunc::vector1",nbands * nbasis * sizeof(std::complex<float>));
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp]: Key word should be `wavefunc::wfcatom`.

File: source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp [hunk 21]
```diff
@@ -255,6 +257,7 @@ void diago_PAO_in_pw_k2(const int &ik,
 	else if(p_wf->init_wfc.substr(0,6)=="atomic")
 	{
 		ModuleBase::ComplexMatrix wfcatom(starting_nw, nbasis);//added by zhengdy-soc
+        ModuleBase::Memory::record("wavefunc::ComplexMatrix",starting_nw * nbasis * sizeof(std::complex<double>));
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp]: Key word should also be "wavefunc::wfcatom"

File: source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp [hunk 22]
```diff
@@ -271,6 +274,7 @@ void diago_PAO_in_pw_k2(const int &ik,
 
 		// (7) Diago with cg method.
 		std::vector<std::complex<float>> s_wfcatom(starting_nw * nbasis);
+        ModuleBase::Memory::record("wavefunc::vector2",starting_nw  * nbasis * sizeof(std::complex<float>));
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp]: Key word should also be `wavefunc::wfcatom`

File: source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp [hunk 23]
```diff
@@ -323,6 +327,7 @@ void diago_PAO_in_pw_k2(const int &ik,
     if (p_wf->init_wfc == "file")
     {
         ModuleBase::ComplexMatrix wfcatom(nbands, nbasis);
+        ModuleBase::Memory::record("wavefunc::wfcatom_2",nbands * nbasis * sizeof(std::complex<double>));
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp]: Key word should also be `wavefunc::wfcatom`

File: source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp [hunk 24]
```diff
@@ -406,6 +411,7 @@ void diago_PAO_in_pw_k2(const int &ik,
     else if (p_wf->init_wfc.substr(0, 6) == "atomic")
     {
         ModuleBase::ComplexMatrix wfcatom(starting_nw, nbasis); // added by zhengdy-soc
+        ModuleBase::Memory::record("wavefunc::wfcatom_3",starting_nw * nbasis * sizeof(std::complex<double>));
```
Comment (dyzheng) [inline source/module_hamilt_pw/hamilt_pwdft/wavefunc.cpp]: also `wavefunc::wfcatom`.

**Review by dyzheng — CHANGES_REQUESTED** [review]
Good for your first PR, please modify with comments.

**Comment by Religious-J** [comment]
> Good for your first PR, please modify with comments.

I get it, I will modify it according to the comments, thanks a lot for your review !

File: source/module_base/clebsch_gordan_coeff.cpp (hunk 1 above)
Comment (Religious-J) [reply source/module_base/clebsch_gordan_coeff.cpp]: Yes, there are some very small parts, I will change to only record the significant parts.

File: source/module_base/module_container/ATen/core/tensor.cpp [hunk 25]
```diff
@@ -216,6 +217,21 @@ void Tensor::resize(const TensorShape& new_shape) {
...
+void Tensor::resize(const TensorShape& new_shape, const std::string& record_str) {
+    if (shape_ == new_shape) {
+        return;
+    }
+    REQUIRES_OK(buffer_->OwnsMemory() || this->NumElements() == 0,
+        "Cannot resize a tensor that mapped from a given data buffer")
+    if (buffer_ && buffer_->GetAllocatedBytes() < new_shape.NumElements() * SizeOfType(data_type_)) {
+        buffer_->unref();
+        this->buffer_ = new TensorBuffer(GetAllocator(device_), new_shape.NumElements() * SizeOfType(data_type_));
+        ModuleBase::Memory::record(record_str,new_shape.NumElements() * SizeOfType(data_type_));
```
Comment (mohanchen) [inline source/module_base/module_container/ATen/core/tensor.cpp:230]: I would not suggest adding new dependencies in tensor module, this module has not been well validated.

Comment (mohanchen) [reply source/module_base/module_container/ATen/core/tensor.cpp:230]: I mean, try not adding memory recorder in tensor.

**Review by dyzheng — APPROVED** [review]
LGTM

File: source/module_hamilt_lcao/module_gint/gint_vl.cpp [hunk 26]
```diff
@@ -99,7 +100,7 @@ void Gint::gint_kernel_dvlocal(
 	//calculating f_mu(r) = v(r)*psi_mu(r)*dv
 	const Gint_Tools::Array_Pool<double> psir_vlbr3 = Gint_Tools::get_psir_vlbr3(
 			this->bxyz, na_grid, LD_pool, block_index, cal_flag, vldr3, psir_ylm.ptr_2D);
-
+	ModuleBase::Memory::record("Gint::gint_kernel_dvlocal",sizeof(double)*this->bxyz*(LD_pool+1)*5);
```
Comment (mohanchen) [inline source/module_hamilt_lcao/module_gint/gint_vl.cpp:103]: It seems not a good practice to record small values such as this.

**Review by mohanchen — CHANGES_REQUESTED** [review]

File: source/module_base/module_container/ATen/core/tensor.cpp (hunk 25 above)
Comment (Religious-J) [reply source/module_base/module_container/ATen/core/tensor.cpp:230]: Ok, I see
