### PR TITLE
Fix: error of non-diagonal nonlocal pseudopotential with LCAO

### LINKED ISSUE #916: Non-zero off-diagonal elements of `PP_DIJ` in pseudopotential should be supported.
## Describe the Bug
The restriction that the off-diagonal elements of `DIJ` (`Pseudopot_upf::dion`) must be zero has been released in [pr910](https://github.com/deepmodeling/abacus-develop/pull/910). However, ABACUS currently only uses diagonal elements for computation, so further updates are needed.

## Expected behavior
Add the support to the non-zero off-diagonal elements of `PP_DIJ` in pseudopotential.

## To Reproduce
The pseudopotential in [test.zip](https://github.com/deepmodeling/abacus-develop/files/8684440/test.zip) has non-zero off-diagonal elements in `PP_DIJ`.

### PR DESCRIPTION
**Pull request by dyzheng**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #916  #4667 

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

File: source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_k.cpp [hunk 1]
```diff
@@ -466,19 +462,15 @@ void Force_LCAO<std::complex<double>>::cal_fvnl_dbeta(const elecstate::DensityMa
...
+                                                ucell.atoms[T0].ncpp.get_d(0, p1, p2, tmp_d);
+                                                for (int ir = 0; ir < 3; ir++)
                                                 {
-                                                    for (int ir = 0; ir < 3; ir++)
-                                                    {
-                                                        nlm1[ir] += nlm_2[ir][ib] * nlm_1[ib]
-                                                                    * ucell.atoms[T0].ncpp.dion(nb, nb);
-                                                    }
-                                                    ib += 1;
+                                                    nlm1[ir] += nlm_2[ir][p1] * nlm_1[p2] * *tmp_d;
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/fvnl_dbeta_k.cpp]: change *tmp_d to（*tmp_d)?

**Comment by mohanchen** [comment]
Add an example to protect this feature?

**Review by mohanchen — APPROVED** [review]

**Review by mohanchen — APPROVED** [review]
