### PR TITLE
perf: sum_band() in pw base; fix: memory leak

### LINKED ISSUE #591: memory leak in MD lcao calculation
## Describe the Bug
In case test/integrate/220_NO_KP_MD_NVE , modify nstep to 1000, the memory raised rapidly every ionic step.

When we tested pw code, it wouldn't happen.
When we tested old non-local pseudopotential calculating method by setting vnl_method=0 in code, the bug wouldn't happen either.

So maybe we can try to solve this memory leak problem.

### PR DESCRIPTION
**Pull request by dyzheng**
1. perf: optimized sum_band() in pw base, ignored unoccupied bands
2. fixed memory leak bug in module_orbital

### CODE REVIEW

File: source/src_pw/charge.cpp [hunk 1]
```diff
@@ -753,6 +753,7 @@ void Charge::sum_band_k(void)
 		{
 			for (int ibnd = 0;ibnd < GlobalV::NBANDS;ibnd++)
 			{
+				if(GlobalC::wf.wg(ik, ibnd)<1e-8) continue;
```
Comment (caic99) [inline source/src_pw/charge.cpp:759]: It's better to add some comments.

**Comment by caic99** [comment]
> range: charge.cpp

If you intend to add a range, it should be under a larger aspect, like some module, but not some files.

**Comment by dyzheng** [comment]
> > range: charge.cpp
> 
> If you intend to add a range, it should be under a larger aspect, like some module, but not some files.
There are still many file not be classified. In future, we definitly should only refer to modules.

**Review by caic99 — APPROVED** [review]
