### PR TITLE
fix: number of processors can be large than FFT grids in the z direction

### LINKED ISSUE #1016: number of processors can not be larger than the number of FFT grids in z direction
## Describe the Bug
When use too many processors, ABACUS will fail with
"Assertion `nrxx > 0' failed."

## To Reproduce
1. [e.g. clone the source code from ...]
2. [e.g. configure CMake with options ...]
3. [e.g. build ABACUS with ...]
4. [e.g. run ABACUS with ...]
It is recommended to attach your calculation case here for the developers to reproduce the bug.

## Environment
- OS: [e.g. Ubuntu 20.04]
- Compiler: [e.g. gcc 5.1.0]
- Dependencies: [e.g. Intel MKL, OpenBLAS]

### PR DESCRIPTION
**Pull request by Qianruipku**
Fix #1016

### CODE REVIEW

**Comment by Qianruipku** [comment]
But how to create integration tests since it needs a lot of processors? Now in our integration tests, we only use 4 processors.

File: source/src_pw/potential.cpp [hunk 1]
```diff
@@ -34,7 +34,6 @@ Potential::~Potential()
 void Potential::allocate(const int nrxx)
 {
     ModuleBase::TITLE("Potential", "allocate");
-    assert(nrxx > 0);
 
     delete[] this->vltot;
     this->vltot = new double[nrxx];
```
Comment (dyzheng) [inline source/src_pw/potential.cpp]: Won't an error be returned during allocating vltot when nrxx <  0 ?

Comment (Qianruipku) [reply source/src_pw/potential.cpp]: Maybe I should change it to assert(nrxx >= 0)

**Comment by dyzheng** [comment]
https://cplusplus.com/reference/new/operator%20new/#:~:text=If%20this%20argument%20is%20zero%2C%20the%20function%20still%20returns%20a%20distinct%20non%2Dnull%20pointer%20on%20success%20(although%20dereferencing%20this%20pointer%20leads%20to%20undefined%20behavior).

File: source/src_pw/potential.cpp (hunk 1 above)
Comment (caic99) [reply source/src_pw/potential.cpp]: > Maybe I should change it to assert(nrxx >= 0)

Please do not use `assert` for it - use if-statement instead.

**Comment by dyzheng** [comment]
How about skip the allocation when size z is zero?

**Comment by Qianruipku** [comment]
There is no mistake when new 0? What's the difference to skip the allocation?

**Comment by caic99** [comment]
> There is no mistake when new 0? What's the difference to skip the allocation?

Hi @Qianruipku ,
Would you read the link that @dyzheng posted above. `new 0` is OK; however, when you delete the address allocated by it, the behavior is undefined.

**Comment by Qianruipku** [comment]
So I need to change to "if(nrxx > 0) this->vltot = new double[nrxx];" ?
And should I delete assert(nrxx >= 0)?

File: source/module_base/tool_quit.cpp [hunk 2]
```diff
@@ -54,9 +54,6 @@ void QUIT(void)
     std::cout<<" See output information in : "<<GlobalV::global_out_dir<<std::endl;
 #endif
 
-#ifdef __MPI
-    MPI_Finalize();
-#endif
```
Comment (caic99) [inline source/module_base/tool_quit.cpp:59]: What't the point deleting `MPI_Finalize()`? This violates MPI standard.

**Review by caic99 — CHANGES_REQUESTED** [review]

**Comment by caic99** [comment]
> #1016

@Qianruipku If your PR is expected to fix this issue, you could write in the form of "Fix #xxx".

**Comment by caic99** [comment]
> So I need to change to "if(nrxx > 0) this->vltot = new double[nrxx];" ? And should I delete assert(nrxx >= 0)?

@Qianruipku 
In your design, what is the expected behavior for the process without FFT grid? Also take part in the following MPI routines (broadcast etc.) without performing actual calculations, or just exit early? 
And, does user know the process number is inappropriate, and the expected process count?

File: source/module_base/tool_quit.cpp (hunk 2 above)
Comment (Qianruipku) [reply source/module_base/tool_quit.cpp:59]: It will make the program stuck. When some processor running warning_quit and other processors do not ，it will stuck

**Comment by Qianruipku** [comment]
> > So I need to change to "if(nrxx > 0) this->vltot = new double[nrxx];" ? And should I delete assert(nrxx >= 0)?
> 
> @Qianruipku In your design, what is the expected behavior for the process without FFT grid? Also take part in the following MPI routines (broadcast etc.) without performing actual calculations, or just exit early? And, does user know the process number is inappropriate, and the expected process count?

When processors are  larger than z grids. all processor still have plane waves.  They will do z-direction FFT.

**Review by dyzheng — APPROVED** [review]

File: source/module_base/tool_quit.cpp (hunk 2 above)
Comment (caic99) [reply source/module_base/tool_quit.cpp:59]: > This violates MPI standard.

I don't think it's good to do so. Any other solution?

Comment (Qianruipku) [reply source/module_base/tool_quit.cpp:59]: If users give wrong input parameters, ABACUS should give warning message and quit at once. There is no need to consider other things for example leak of memories. Because ABACUS is killed.

**Review by caic99 — APPROVED** [review]

**Comment by caic99** [comment]
> When processors are larger than z grids. all processor still have plane waves. They will do z-direction FFT.

In this case, would efficiency downgrades, because some processes are partly free? If so, does the user know what is the best value for number of processes?

**Comment by Qianruipku** [comment]
> In this case, would efficiency downgrades, because some processes are partly free? If so, does the user know what is the best value for number of processes?

More cores can accelerate the calculation.  We may help the user choose the best parallel plan like ABINIT  in the future.
