### PR TITLE
Bug: fix print Error of nspin with noncolin=1

### LINKED ISSUE #3239: Bug: wrong print of "NSPIN=1" in OUT.prefix/INPUT file with noncolin=1
### Describe the bug

When I run `204_NO_KP_NC` with `noncolin=1`, and check that `nspin` is 1 in `OUT.autotest/INPUT` , which is expected to be 4.

### Expected behavior

fix it.

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by WHUweiqingzhou**
Fix #3239

### CODE REVIEW

File: source/module_io/input.cpp [hunk 1]
```diff
@@ -3377,6 +3377,11 @@ void Input::Default_2(void) // jiyy add 2019-08-04
             }
         }
     }
+    // set nspin with noncolin
+    if (noncolin)
```
Comment (dyzheng) [inline source/module_io/input.cpp]:
```suggestion
    if (noncolin || lspinorb)
```

**Review by dyzheng — APPROVED** [review]
