### PR TITLE
Fix: add a check_rho() to avoid negative charge density (Useful to know that the initial charge density could not be negative)

### LINKED ISSUE #4046: Should negative charge density of spin down electrons be allowed in ABACUS?
### Details

In NSPIN=2 case, if we assign a magnetism value that exceeds the total number of electrons (nelec) in the cell - for instance, setting magnetism to 20 when nelec equals 10 - the initialized charge density will comprise 15 spin-up electrons and **-5 spin-down** electrons. Although this situation does not disrupt the calculation and may even yield the correct result, it raises the question of whether such an unphysical case should be permitted.
Corresponding code can be found in `atomic_rho` within the file `/module_elecstate/module_charge/charge.cpp`.
image

In QE, the `starting_magnetization` is limited between -1 and 1, thereby preventing the occurrence of negative charge densities.
The description of `starting_magnetization` is as follow:
image
Corresponding code in QE is:
image

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

### PR DESCRIPTION
**Pull request by WHUweiqingzhou**
Fix #4046.

### The List of Charges
1. add a new `check_rho()` in `charge.h`
2. run `check_rho()` after `init_rho()`
3. rename `check_ne()` as `cal_rho2ne()`

After this PR, if you set a not good initial magnetic moment, like:
```bash
Fe
1.0
2
0.0 0.0 0.0    mag 33
0.5 0.5 0.5    mag 0
```
and you will get the quit:
```
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 Spin-Down Charge is negative! Please set the initial magnetic moment correctly!
 CHECK IN FILE : OUT.ABACUS/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### CODE REVIEW

File: source/module_elecstate/module_charge/charge.cpp [hunk 1]
```diff
@@ -711,12 +711,45 @@ double Charge::check_ne(const double* rho_in) const
...
+        }
+    }
+    else if (this->nspin == 2)
+    {
+        // for spin up
+        double ne_up = 0.0;
+        ne_up = this->cal_rho2ne(rho[0]);
+        if (ne_up < 0.0)
+        {
+            ModuleBase::WARNING_QUIT("Charge", "Spin-Up Charge is negative! Please set the initial magnetic moment correctly!");
```
Comment (kirk0830) [inline source/module_elecstate/module_charge/charge.cpp]:
```suggestion
            ModuleBase::WARNING_QUIT("Charge", "Number of spin-down electrons set in starting magnetization exceeds all available.");
```

File: source/module_elecstate/module_charge/charge.cpp [hunk 2]
```diff
@@ -711,12 +711,45 @@ double Charge::check_ne(const double* rho_in) const
...
+        }
+        // for spin down
+        double ne_dn = 0.0;
+        ne_dn = this->cal_rho2ne(rho[1]);
+        if (ne_dn < 0.0)
+        {
+            ModuleBase::WARNING_QUIT("Charge", "Spin-Down Charge is negative! Please set the initial magnetic moment correctly!");
```
Comment (kirk0830) [inline source/module_elecstate/module_charge/charge.cpp]:
```suggestion
            ModuleBase::WARNING_QUIT("Charge", "Number of spin-up electrons set in starting magnetization exceeds all available.");
```

File: source/module_elecstate/module_charge/charge.cpp [hunk 3]
```diff
@@ -711,12 +711,45 @@ double Charge::check_ne(const double* rho_in) const
...
     ne = ne * elecstate::get_ucell_omega() / (double)this->rhopw->nxyz;
-    std::cout << std::setprecision(10);
-    std::cout << " check the electrons number from rho, ne =" << ne << std::endl;
-    std::cout << std::setprecision(6);
+
     return ne;
 }
 
+void Charge::check_rho()
+{
```
Comment (kirk0830) [inline source/module_elecstate/module_charge/charge.cpp:719]: better to print out the "expected charge" and "charge afte renormalization", I suppose

**Review by kirk0830 — APPROVED** [review]
