### PR TITLE
fix : calculate dos_smearing without reading DOS first

### LINKED ISSUE #746: Bug for 107_PW_OD_outputdos
## Describe the Bug
Sometime, 107_PW_OD_outputdos cannot pass the autotest

## To Reproduce
0. Download develop branch
1. Compile it with Makefile
2. Test 107_PW_OD_outputdos
3. Repeat  until it shows ERROR: 
Sometimes it is OK:
图片
sometimes it is wrong:
图片
[result.txt](https://github.com/deepmodeling/abacus-develop/files/8130648/result.txt)

## Environment
- OS: Ubuntu16.04
- Compiler: oneapi2021
- Optional Dependencies: [e.g. Intel MKL]

### PR DESCRIPTION
**Pull request by wenfei-li**
The reason behind this bug is that in calculating DOS_smearing, the program first takes the calculated DOS as input:
```cpp
			 for(int i=0;i<number;i++)
			 {
				 in >> energy[i] >> dos[i];
			 }
			 if(!in.eof())
			 {
				 //std::cout<<"\n Read Over!"<<std::endl;
			 }
			 in.close();
```
This might have something to do with the input buffer. Also, it is bad practice to use the output file of the program as input file.
The way to fix this is to save the array that stores DOS and use that in calculating DOS_smearing, instead of reading from DOS.

### CODE REVIEW

File: source/src_io/dos.cpp [hunk 1]
```diff
@@ -157,10 +158,15 @@ bool Dos::calculate_dos
...
 	std::ofstream ofs;
+	std::ofstream ofs1;
 	if(GlobalV::MY_RANK==0)
 	{
 		ofs.open(fa.c_str());//make the file clear!!
+		ofs1.open(fa1.c_str());//make the file clear!!
 	}
+	std::vector<double> dos;
+	std::vector<double> ene;
+	std::vector<double> dos2; //dos_smearing
```
Comment (caic99) [inline source/src_io/dos.cpp]: You are using both '1' and '2' in variable names for smearing file output. Using "dos_smering" or something like that instead of numbers will be better.

**Comment by caic99** [comment]
Hi @wenfei-li ,
Thank you for your work!
You can attach the detail of bug in PR description (exactly the thing you replied in #746 ), and summarize this bug in PR subject.

File: source/src_io/dos.cpp (hunk 1 above)
Comment (wenfei-li) [reply source/src_io/dos.cpp]: sounds good

**Comment by wenfei-li** [comment]
> Hi @wenfei-li , Thank you for your work! You can attach the detail of bug in PR description (exactly the thing you replied in #746 ), and summarize this bug in PR subject.

not sure how to do that :P

**Review by caic99 — APPROVED** [review]
