### PR TITLE
Test: add unitcell_test_r for UnitCell reading pp

### LINKED ISSUE #2008: read_pseudo called after bcast_unitcell_pseudo
### Describe the bug

Which will cause arbitrary values of meshx, natomwfc, lmax, and lmax_ppwf

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hongriTianqi**
Fix #2008

### CODE REVIEW

File: source/module_cell/unitcell.cpp [hunk 1]
```diff
@@ -932,6 +930,10 @@ void UnitCell::read_pseudo(ofstream &ofs)
     }
 
     cal_meshx();
+
+#ifdef __MPI
+    bcast_unitcell_pseudo();
```
Comment (dyzheng) [inline source/module_cell/unitcell.cpp]: @YuLiu98 can you look at this modification? It looks related with PR #1926

**Review by dyzheng — APPROVED** [review]
