### PR TITLE
Fix some output information typo

### LINKED ISSUE #6131: Possible typo of INPUT docs: test_stress INPUT keyword
### Details

What does it mean by "Specify whether to set the colorful output in terminal." of `test_stress` INPUT keyword?
Image
Maybe it is a typo or some description of a deprecated parameter by mistake?

### Have you read the online manual http://abacus.deepmodeling.com/en/latest/

- [x] Yes, I have read the online manual.

### Task list for Issue attackers (only for developers)

- [ ] Identify the specific section of the documentation with the issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Update the documentation to address the issue, following the suggested improvement.
- [ ] Ensure the updated documentation adheres to the project's documentation standards.
- [ ] Test the updated documentation to ensure it is clear and accurate.
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Publish the updated documentation and notify the issue reporter.

### PR DESCRIPTION
**Pull request by mohanchen**
Fix #6131 , add information in the WARNING_QUIT function

### CODE REVIEW

File: source/module_cell/read_atom_species.cpp [hunk 1]
```diff
@@ -141,7 +141,7 @@ bool read_lattice_constant(std::ifstream& ifa,
         ModuleBase::GlobalFunc::READ_VALUE(ifa, lat0);
         if(lat0<=0.0)
         {
-            ModuleBase::WARNING_QUIT("read_atom_species","lat0<=0.0");
+            ModuleBase::WARNING_QUIT("read_atom_species","lattice constant <= 0.0");
```
Comment (Cstandardlib) [inline source/module_cell/read_atom_species.cpp:144]: There is a test clause in `module_cell/test/unitcell_test.cpp` that reads a string "lat0<=0.0" from warning output, which needs to be amended together.
Please see:
https://github.com/deepmodeling/abacus-develop/blob/072d03edc28d2470dfc0ee93b75c8d3a3622f0f5/source/module_cell/test/unitcell_test.cpp#L1213

File: source/module_cell/read_atom_species.cpp [hunk 2]
```diff
@@ -64,7 +64,7 @@ bool read_atom_species(std::ifstream& ifa,
                     {
                         GlobalV::ofs_warning << "unrecongnized pseudopotential type: " 
                         << one_string << ", check your STRU file." << std::endl;
-                        ModuleBase::WARNING_QUIT("read_atom_species", "unrecongnized pseudo type.");
```
Comment (Cstandardlib) [inline source/module_cell/read_atom_species.cpp:67]: There is test clause in `module_cell/test/unitcell_test.cpp` that reads a string "unrecongnized pseudo type.", which needs to be modified together.

https://github.com/deepmodeling/abacus-develop/blob/072d03edc28d2470dfc0ee93b75c8d3a3622f0f5/source/module_cell/test/unitcell_test.cpp#L1195

File: source/module_cell/read_atoms.cpp [hunk 3]
```diff
@@ -547,7 +548,7 @@ bool unitcell::read_atom_positions(UnitCell& ucell,
     //check if any atom can move in MD
     if(!ucell.if_atoms_can_move() && PARAM.inp.calculation=="md" && PARAM.inp.esolver_type!="tddft")
     {
-        ModuleBase::WARNING("read_atoms", "no atom can move in MD!");
+        ModuleBase::WARNING("read_atoms", "no atoms can move in MD simulations!");
```
Comment (Cstandardlib) [inline source/module_cell/read_atoms.cpp:551]: There is test clause in `module_cell/test/unitcell_test.cpp` that reads a string "no atom can move in MD!", which needs to be modified together.

https://github.com/deepmodeling/abacus-develop/blob/072d03edc28d2470dfc0ee93b75c8d3a3622f0f5/source/module_cell/test/unitcell_test.cpp#L1911

**Review by Cstandardlib — COMMENTED** [review]
There are 2 left issues the same as above.

**Review by Cstandardlib — APPROVED** [review]
