### PR TITLE
Test: add a new UnitTest to protect `save_DMR()`

### LINKED ISSUE #3621: Bug: some cell-relax calculations cannot run normally after `mixing_restart` with `mixing_dmr`
### Describe the bug

some tests show a bug occurs sometimes if `mixing_dmr = 1`, the calculations will be stopped after `mixing_restart` at the second relaxation step.
https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.95-5ad687

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by WHUweiqingzhou**
Fix #3621

### CODE REVIEW

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 #include "gmock/gmock.h"
 #include "gtest/gtest.h"
+#define private public
```
Comment (kirk0830) [inline source/module_elecstate/module_dm/test/test_dm_R_init.cpp:5]: I have to say due to present program structure, this is a rather rude way to get access to private member who seems should have a `getter` function or something should be tested in another way but, this indicates there should be a re-design on the class in which those mistakenly set as private variables (and even functions) and, certainly a refactor, although it may be not of high priority.

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp [hunk 2]
```diff
@@ -276,6 +277,38 @@ TEST_F(DMTest, DMInit4)
...
+    kv->kvec_d.resize(nks);
+    kv->kvec_d[1].x = 0.5;
+    kv->kvec_d[3].x = 0.5;
+    // construct a DM
+    elecstate::DensityMatrix<std::complex<double>, double> DM(kv, paraV, nspin);
+    Grid_Driver gd(0, 0, 0);
+    DM.init_DMR(&gd, &ucell);
+    // construct another DM
+    elecstate::DensityMatrix<std::complex<double>, double> DM_test(kv, paraV, nspin);
+    DM_test.init_DMR(*DM.get_DMR_pointer(1));
```
Comment (kirk0830) [inline source/module_elecstate/module_dm/test/test_dm_R_init.cpp:298]: I just leave comment about the function `get_*_pointer` here but not critize your unittest: I would say most of time the function to directly get raw pointer should not be called and the class which owns the variable that the pointer points to should have another design for accessing its variables, even if it is an array.
Get pointer-like operations should only be used in some functions like lapack, ...

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp [hunk 3]
```diff
@@ -276,6 +277,38 @@ TEST_F(DMTest, DMInit4)
...
 }
 
+// test for save_DMR
+TEST_F(DMTest, saveDMR)
+{
+    // initalize a kvectors
+    K_Vectors* kv = nullptr;
+    int nspin = 2;
+    int nks = 4; // since nspin = 2
+    kv = new K_Vectors;
```
Comment (kirk0830) [inline source/module_elecstate/module_dm/test/test_dm_R_init.cpp:287]: Maybe you can directly create an instance of `K_Vectors` class instead of allocate memory in heap explicitly. If you really want some features of pointer, I would suggest use `std::shared_ptr<K_Vectors>` or `std::unique_ptr<K_Vectors>`, they are C++ 11 smart pointer and can manage memory for you automatically, which means, more safe, but present is also okay because this test code is simple

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp (hunk 1 above)
Comment (WHUweiqingzhou) [reply source/module_elecstate/module_dm/test/test_dm_R_init.cpp:5]: I understand this. However, the get function of `_DMR_save` will never be called in main code. I do not think define a get-function only for UnitTest is a good idea.

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp (hunk 2 above)
Comment (WHUweiqingzhou) [reply source/module_elecstate/module_dm/test/test_dm_R_init.cpp:298]: Got it! Thanks for the information.

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp (hunk 3 above)
Comment (WHUweiqingzhou) [reply source/module_elecstate/module_dm/test/test_dm_R_init.cpp:287]: Forgot to delete `kv`, I have added it.

Comment (WHUweiqingzhou) [reply source/module_elecstate/module_dm/test/test_dm_R_init.cpp:287]: > Maybe you can directly create an instance of `K_Vectors` class instead of allocate memory in heap explicitly. If you really want some features of pointer, I would suggest use `std::shared_ptr<K_Vectors>` or `std::unique_ptr<K_Vectors>`, they are C++ 11 smart pointer and can manage memory for you automatically, which means, more safe, but present is also okay because this test code is simple

Forgot to delete kv, I have added it.

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp (hunk 2 above)
Comment (WHUweiqingzhou) [reply source/module_elecstate/module_dm/test/test_dm_R_init.cpp:298]: > I just leave comment about the function `get_*_pointer` here but not critize your unittest: I would say most of time the function to directly get raw pointer should not be called and the class which owns the variable that the pointer points to should have another design for accessing its variables, even if it is an array. Get pointer-like operations should only be used in some functions like lapack, ...

Got it! Thanks for the information.

File: source/module_elecstate/module_dm/test/test_dm_R_init.cpp (hunk 1 above)
Comment (WHUweiqingzhou) [reply source/module_elecstate/module_dm/test/test_dm_R_init.cpp:5]: > I have to say due to present program structure, this is a rather rude way to get access to private member who seems should have a `getter` function or something should be tested in another way but, this indicates there should be a re-design on the class in which those mistakenly set as private variables (and even functions) and, certainly a refactor, although it may be not of high priority.

I understand this. However, the get function of `_DMR_save` will never be called in main code. I do not think define a get-function only for UnitTest is a good idea.

**Review by dyzheng — APPROVED** [review]
LGTM
