### PR TITLE
Fix the bug that the Wannier90 interface does not report error informations when reading files under MPI.

### LINKED ISSUE #3505: wannier90 for LCAO can not running in nscf
### Describe the bug

[3_abacus_nscf.tar.gz](https://github.com/deepmodeling/abacus-develop/files/13960436/3_abacus_nscf.tar.gz)
Please see the example, when I running a nscf to output wannier function, Screen output always shows "KILLED BY SIGNAL: 9 (Killed)", and nscf log stop with "spin1final_state".

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by jingan-181**
Fix the bug that the Wannier90 interface does not report error informations when reading files under MPI.

### Reminder
- [x] Have you linked an issue with this pull request?
- [x] Have you noticed possible changes of behavior below or in the linked issue?
- [x] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #3505 

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### CODE REVIEW

File: source/module_io/to_wannier90.cpp [hunk 1]
```diff
@@ -78,6 +78,80 @@ void toWannier90::read_nnkp(const K_Vectors& kv)
...
+            {
+                eig_file << std::setw(5) << ib + 1 << std::setw(5) << ik + 1 - start_k_index << std::setw(18)
+                         << std::showpoint << std::fixed << std::setprecision(12)
+                         << ekb(ik, cal_band_index[ib]) * ModuleBase::Ry_to_eV << std::endl;
+            }
+        }
+
+        eig_file.close();
+    }
+#else
```
Comment (Liu-RX) [inline source/module_io/to_wannier90.cpp]: The `#else` could be moved to the place after `if (GlobalV::MY_RANK == 0)` in line 104, so that the code block after `#else` (line 121-133, which is a duplicate of line 106-118) could be deleted.

Comment (jingan-181) [reply source/module_io/to_wannier90.cpp]: This cannot be done, moving `#else` after line 104 will cause MPI compilation errors, because only `if (GlobalV::MY_RANK == 0)` exists.

Comment (jingan-181) [reply source/module_io/to_wannier90.cpp]: I will remove the `__MPI` macro definition under the `out_eig` function, which applies to both serial and MPI.

Comment (Liu-RX) [reply source/module_io/to_wannier90.cpp]: I mean changing line 103-105 to 
```
#ifdef __MPI
    if (GlobalV::MY_RANK == 0)
#endif
{...}
```
I think this works.

Comment (jingan-181) [reply source/module_io/to_wannier90.cpp]: I understand what you mean, and I modified it according to your suggestion.

**Review by Liu-RX — APPROVED** [review]

**Review by Liu-RX — APPROVED** [review]

**Review by Liu-RX — APPROVED** [review]

**Review by dyzheng — APPROVED** [review]
LGTM
