### PR TITLE
[Fix]Enable abacus to be compiled with CXX 17 & CUDA 13

### LINKED ISSUE #6752: CUDA 13 requires C++ 17
### Describe the bug

CMake only sets `CMAKE_CUDA_STANDARD` to 14, and it cannot be overridden, leading to the following error:

```
/home/conda/feedstock_root/build_artifacts/abacus_1764559181076/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/targets/x86_64-linux/include/cccl/thrust/detail/config/cpp_dialect.h:78:6: error: #error Thrust requires at least C++17. Define CCCL_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
   78 | #    error Thrust requires at least C++17. Define CCCL_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
      |      ^~~~~
```

### Expected behavior

Set `CMAKE_CUDA_STANDARD` to 17 for CUDA 13.

Need a fix for both develop and lts.

### To Reproduce

See https://github.com/conda-forge/abacus-feedstock/pull/78

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by ZhouXY-PKU**
### Linked Issue
Fix #6752 
See also https://github.com/conda-forge/abacus-feedstock/pull/78

### Unit Tests and/or Case Tests for my changes
- This PR is a refactoring to improve maintainability and forward-compatibility. No new unit tests are added, as all existing functionality is intended to remain unchanged. The project's existing regression test suite is used to verify that this refactoring does not introduce any regressions across supported CUDA versions.

### What's changed?
This PR introduces a CUDA compatibility layer to prepare the codebase for CUDA 13 support and centralize version-specific logic. The key changes are:
1.  New Compatibility Module: Modified and added `source/source_base/module_device/cuda_compat.h` and `cuda_compat.cpp`. This module acts as an abstraction layer to handle differences between CUDA versions.
2.  API Compatibility: It provides a version-agnostic implementation for `cufftGetErrorString`, which has removed error codes in CUDA 13. 
3.  Code Refactoring: Deprecated CUDA device properties (like `clockRate`, `memoryClockRate`, etc) which were removed in CUDA 13 have been moved from `output_device.cpp` into the new compatibility layer. This cleans up the main application logic and isolates version-specific code.
4.  Build System Update: `CMakeLists.txt` was updated to include the new source files.
The primary impact is that ABACUS can now be built with CUDA 13 without modifying the main application code. This also improves long-term maintainability by creating a dedicated place for future CUDA compatibility fixes.

###  Any changes of core modules? (ignore if not applicable)
There are no changes to the core solver modules (`ESolver`, `HSolver`, `ElecState`, `Hamilt`, `Operator`, or `Psi`). The changes are contained within the `module_device` infrastructure layer. The purpose of this refactoring is to abstract away hardware/driver-specific details from the core scientific modules, ensuring they remain unaffected by changes in the underlying CUDA toolkit.

### CODE REVIEW

File: source/source_base/module_device/cuda_compat.cpp [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+//---------------------------------------------------------------------------
+void printDeprecatedDeviceInfo(std::ostream& ofs_device, const cudaDeviceProp& deviceProp) 
+{
+#if defined(CUDA_VERSION) && CUDA_VERSION < 13000
+  char msg[1024];
+  sprintf(msg,
+          "  GPU Max Clock rate:                            %.0f MHz (%0.2f "
+          "GHz)\n",
+          deviceProp.clockRate * 1e-3f, deviceProp.clockRate * 1e-6f);
+  ofs_device << msg << std::endl;
```
Comment (Cstandardlib) [inline source/source_base/module_device/cuda_compat.cpp:17]: Is it necessory to use `snprintf`, or directly C++ style `ofs_device` to output device info?

**Review by Cstandardlib — APPROVED** [review]
Nice Job!

File: source/source_base/module_device/cuda_compat.cpp (hunk 1 above)
Comment (ZhouXY-PKU) [reply source/source_base/module_device/cuda_compat.cpp:17]: The original `output_device.cpp` used that, and I just moved the code block into `cuda_compat.cpp`without any changes. Maybe you have better solutions?

**Review by mohanchen — APPROVED** [review]

**Comment by Flying-dragon-boxing** [comment]
Current implementation of `CMakeLists.txt` doesn't really detect the CUDA version. The CUDA version is a manually-defined variable, making this CXX 17 issue not automatically solved. 
```cmake
  if(CUDA_VERSION VERSION_GREATER_EQUAL "13.0")
    message(STATUS "CUDA ${CUDA_VERSION} detected. Setting CMAKE_CUDA_STANDARD to 17.")
    set_if_higher(CMAKE_CXX_STANDARD 17)
  endif()
```
Actually when executing `find_package(CUDAToolkit REQUIRED)`, CMake automatically introduces a variable `CUDAToolkit_VERSION`. Is there any difficulty introducing this variable in your situation?
