### PR TITLE
fix: pseudopotenital "Al.pz-vbc.UPF" not recognized

### LINKED ISSUE #643: Job "Aborted (core dumped)" when using Al.pz-vbc.UPF Pseudopotential
In this case, ABACUS can not running when the pseudopotential is by using "Al.pz-vbc.UPF", and the error is:
abacus: /home/pxl/abacus-develop/source/src_pw/charge.cpp:253: lambda []()->std::vector<double, std::allocator<double>>::operator()()->std::vector<double, std::allocator<double>>: Assertion `charge!=0.0 || charge==atom->zv' failed.
Aborted (core dumped)

pseudopotential "Al.pz-vbc.UPF" is from QE, when I running the examples in QEPATH/PW/examples/example01, QE auto download it from internet.
[al-scf-cg.zip](https://github.com/deepmodeling/abacus-develop/files/7882561/al-scf-cg.zip)

### PR DESCRIPTION
**Pull request by sunliang98**
< fix >
Fix the bug mentioned by issue#643, where the key word "<PP_RHOATOM>", "<PP_RAB>", "<PP_DIJ>", and "<PP_R>" in pseudopotenital "Al.pz-vbc.UPF" can't be recognized by read_pp_upf201.cpp.
By adding codes in read_pp_upf201.cpp to recognize these key words.
< test >
Add a test named "101_PW_upf201_Al_pseudopots" to ensure the pseudopotentials like "Al.pz-vbc.UPF" can be read successfully.

### CODE REVIEW

File: source/module_cell/read_pp_upf201.cpp [hunk 1]
```diff
@@ -230,19 +254,37 @@ int Pseudopot_upf::read_pseudo_upf201(std::ifstream &ifs)
...
-			ifs >> dion(i,j);
-			if ( i != j  && dion(i,j) != 0.0 )
+			for(int j=0;j<nbeta;j++)
 			{
-				std::cout << " error: for i != j, Dij of Pseudopotential must be 0.0 " << std::endl;
-				exit(1);
+				ifs >> dion(i,j);
+				if ( i != j  && dion(i,j) != 0.0 )
+				{
+					std::cout << " error: for i != j, Dij of Pseudopotential must be 0.0 " << std::endl;
```
Comment (caic99) [inline source/module_cell/read_pp_upf201.cpp]: Maybe use `WARNING_QUIT`here is better? @dyzheng

Comment (dyzheng) [reply source/module_cell/read_pp_upf201.cpp]: Yes, please use the global function rather than raw cout and exit code.

File: source/module_cell/read_pp_upf201.cpp [hunk 2]
```diff
@@ -132,28 +132,52 @@ int Pseudopot_upf::read_pseudo_upf201(std::ifstream &ifs)
...
+    if (ModuleBase::GlobalFunc::SCAN_BEGIN(ifs, "<PP_RAB"))
 	{
-		ifs >> this->rab[ir];
+		ModuleBase::GlobalFunc::READ_VALUE(ifs, word); // type size columns
+		for (int ir = 0;ir < mesh;ir++)
+		{
+			ifs >> this->rab[ir];
+		}
+	}
+	else if (ModuleBase::GlobalFunc::SCAN_BEGIN(ifs, "<PP_RAB>"))
```
Comment (dyzheng) [inline source/module_cell/read_pp_upf201.cpp:149]: Please don't repeat the code.
You can use inline function or other method.

File: source/module_cell/read_pp_upf201.cpp [hunk 3]
```diff
@@ -230,19 +254,37 @@ int Pseudopot_upf::read_pseudo_upf201(std::ifstream &ifs)
...
+				ifs >> dion(i,j);
+				if ( i != j  && dion(i,j) != 0.0 )
+				{
+					std::cout << " error: for i != j, Dij of Pseudopotential must be 0.0 " << std::endl;
+					exit(1);
+				}
+			}
+		}
+	}
+	else if ( ModuleBase::GlobalFunc::SCAN_BEGIN(ifs, "<PP_DIJ>"))
```
Comment (dyzheng) [inline source/module_cell/read_pp_upf201.cpp:234]: Please don't repeat the code.
You can use inline function or other method.

File: source/module_cell/read_pp_upf201.cpp [hunk 4]
```diff
@@ -302,14 +344,26 @@ int Pseudopot_upf::read_pseudo_upf201(std::ifstream &ifs)
...
+		ModuleBase::GlobalFunc::READ_VALUE(ifs, word); // type size columns
+		delete[] rho_at;
+		this->rho_at = new double[mesh];
+		ModuleBase::GlobalFunc::ZEROS(rho_at, mesh);
+		for (int ir = 0;ir < mesh;ir++)
+		{
+			ifs >> this->rho_at[ir];
+		}
+	}
+	else if (ModuleBase::GlobalFunc::SCAN_BEGIN(ifs, "<PP_RHOATOM>"))
```
Comment (dyzheng) [inline source/module_cell/read_pp_upf201.cpp:299]: Please don't repeat the code.
You can use inline function or other method.

File: source/module_cell/read_pp_upf201.cpp [hunk 5]
```diff
@@ -132,28 +132,52 @@ int Pseudopot_upf::read_pseudo_upf201(std::ifstream &ifs)
...
+		this->r = new double[mesh];
+		this->rab = new double[mesh];
+		ModuleBase::GlobalFunc::ZEROS(r,mesh);
+		ModuleBase::GlobalFunc::ZEROS(rab,mesh);
+		for (int ir = 0;ir < mesh;ir++)
+		{
+			ifs >> this->r[ir];
+		}
+	}
+	else if (ModuleBase::GlobalFunc::SCAN_BEGIN(ifs, "<PP_R>"))
```
Comment (dyzheng) [inline source/module_cell/read_pp_upf201.cpp:138]: Please don't repeat the code.
You can use inline function or other method.

**Review by dyzheng — CHANGES_REQUESTED** [review]

File: source/module_cell/read_pp_upf201.cpp (hunk 1 above)
Comment (sunliang98) [reply source/module_cell/read_pp_upf201.cpp]: OK, I have replaced `exit` with `WARNING_OUIT`.

File: source/module_cell/read_pp_upf201.cpp (hunk 5 above)
Comment (sunliang98) [reply source/module_cell/read_pp_upf201.cpp:138]: Inline function can't contain for-loop, so I define four auxiliary functions to aviod repeating the code.

**Review by dyzheng — APPROVED** [review]
