### PR TITLE
Add use sw and fix Floating point exception 

### LINKED ISSUE #6355: Floating point exception, which may lead to bugs
### Describe the bug

when i  run the abacus in sunway, i find many  Floating point exception.
1. 
Error in the division by zero,the array atom->ncpp.r may have zero,thus the r2 may zero,it is a undefined behavior
Image
2. the Non-standard number
If the value of cell.atoms[it].ncpp.betar is less than 1e-308, it is directly set to 0 on Intel, but on Sunway, for some reason, it appears as a non-normalized integer, which prevents any calculations from being performed.Actullay if a double value less than 1e-300,it can be set as zero to avoid the problem in other meachine.

Image
3.
the array rho_basis->gg may have zero,thus there is an error in the division by zero ,it is a undefined behavior.
Image

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by A-006**
### Linked Issue
Fix #6355

### Unit Tests and/or Case Tests for my changes
- Test the 01_PW/performance on sw,the results has been pasted here.
[output.xlsx](https://github.com/user-attachments/files/21153698/output.xlsx)

### What's changed?
- We have successfully enabled ABACUS compilation on the sw architecture by setting use_sw=on. Additionally, we configured SW_MATH and SW_FFT to properly reference the mathematical libraries (including BLAS, LAPACK, and ScaLAPACK) optimized for sw processors.
- Fixed floating-point errors and undefined behaviors reported in issue #6355, which involved division by zero operations and the use of non-standard numerical values.
- Implemented standardization for the handling of gg0 (plane wave modulus with zero values). Previously, the code employed various inconsistent approaches (such as using ig0_index or setting minimum thresholds) to avoid division by zero. This unification improves code clarity and maintainability by establishing a consistent method for zero-value handling.

### Attention
- Now the abacus does not support the sw FFT,it will be add later.
- Now it doesn't support the SCAN,it is a diffcult to compile the libxc on the sunway meachine.

### CODE REVIEW

File: source/source_estate/module_pot/H_Hartree_pw.cpp [hunk 1]
```diff
@@ -44,18 +44,18 @@ ModuleBase::matrix H_Hartree_pw::v_hartree(const UnitCell &cell,
...
     std::vector<std::complex<double>> vh_g(rho_basis->npw);
+    const int ig0 = rho_basis->ig_gge0;
 #ifdef _OPENMP
 #pragma omp parallel for reduction(+:ehart)
 #endif
     for (int ig = 0; ig < rho_basis->npw; ig++)
     {
-        if (rho_basis->gg[ig] >= 1.0e-8) // LiuXh 20180410
-        {
+        if (ig == ig0) continue; // skip G=0
```
Comment (mohanchen) [inline source/source_estate/module_pot/H_Hartree_pw.cpp]: strange here,

File: source/source_pw/module_pwdft/stress_func_cc.cpp [hunk 2]
```diff
@@ -159,8 +159,7 @@ void Stress_Func<FPTYPE, Device>::stress_cc(ModuleBase::matrix& sigma,
 			for(int ig = 0;ig< rho_basis->npw;ig++)
 			{
 				const FPTYPE norm_g = sqrt(rho_basis->gg[ig]);
-				if(norm_g < 1e-4) { 	continue;
-}
+				if(norm_g < 1e-4) { 	continue;}
```
Comment (mohanchen) [inline source/source_pw/module_pwdft/stress_func_cc.cpp]: one line for { and }

File: source/source_pw/module_pwdft/VNL_in_pw.cpp [hunk 3]
```diff
@@ -724,21 +724,42 @@ void pseudopot_cell_vnl::init_vnl(UnitCell& cell, const ModulePW::PW_Basis* rho_
...
                 for (int ir = 0; ir < kkbeta; ir++)
-                {
-                    aux[ir] = cell.atoms[it].ncpp.betar(ib, ir) * jl[ir] * cell.atoms[it].ncpp.r[ir];
+                {   
+		            aux[ir] = cell.atoms[it].ncpp.betar(ib, ir) * jl[ir] * cell.atoms[it].ncpp.r[ir];   
                 }
-                double vqint;
-                ModuleBase::Integral::Simpson_Integral(kkbeta, aux, cell.atoms[it].ncpp.rab.data(), vqint);
+
+		double vqint;
```
Comment (mohanchen) [inline source/source_pw/module_pwdft/VNL_in_pw.cpp]: initialize the variable, and more spaces are needed

File: source/source_pw/module_pwdft/VNL_in_pw.cpp [hunk 4]
```diff
@@ -724,21 +724,42 @@ void pseudopot_cell_vnl::init_vnl(UnitCell& cell, const ModulePW::PW_Basis* rho_
...
         double* jl = new double[kkbeta];
         double* aux = new double[kkbeta];
-
+        #ifdef __SW
+        for (int ib = 0; ib < nbeta; ib++)
+        {
+            int flag = 0;
+            for (int ir = 0; ir < kkbeta; ir++)
+            {
+                if (std::abs(cell.atoms[it].ncpp.betar(ib, ir)) < 1e-280)
```
Comment (Cstandardlib) [inline source/source_pw/module_pwdft/VNL_in_pw.cpp]: Does the magic number 1e-280 have any special numerical or physical meaning here?👀

Comment (A-006) [reply source/source_pw/module_pwdft/VNL_in_pw.cpp]: This parameter is measured by the machine and can potentially be configured as 1e-200.

File: source/source_pw/module_pwdft/stress_func_cc.cpp (hunk 2 above)
Comment (A-006) [reply source/source_pw/module_pwdft/stress_func_cc.cpp]: The brace has been added.

File: source/source_estate/module_pot/H_Hartree_pw.cpp (hunk 1 above)
Comment (A-006) [reply source/source_estate/module_pot/H_Hartree_pw.cpp]: The judgment has been changed.

File: source/source_pw/module_pwdft/VNL_in_pw.cpp (hunk 3 above)
Comment (A-006) [reply source/source_pw/module_pwdft/VNL_in_pw.cpp]: The data has been initialized.

**Review by mohanchen — APPROVED** [review]
