### PR TITLE
Fix: Veff error when MPI_threads larger than nz

### LINKED ISSUE #1181: Fault when number of cores are larger than z fft grids.
### Describe the bug

[Htest.tar.gz](https://github.com/deepmodeling/abacus-develop/files/9386200/Htest.tar.gz)
if we use mpirun -np 16 abacus, error occurs:
image
However previous commit 7b86acbeb842e4dc52f8d03f5f573bfe3541b406 is OK:
image

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by dyzheng**
In the test case 101_PW_15_lowz, Ewald enengy would be error with nz=3.
One new parameter is added for this test case: test_skip_ewald, if this parameter is set to true, ewald calculation would be skipped.
This is a test-only parameter, which is hidden to users.

### CODE REVIEW

File: source/module_hamilt/ks_pw/veff_pw.cpp [hunk 1]
```diff
@@ -46,38 +46,47 @@ void Veff<OperatorPW>::act
     {
         if (this->npol == 1)
         {
-            const double* current_veff = &(this->veff[0](current_spin, 0));
             wfcpw->recip2real(tmpsi_in, porter, ik);
-            for (int ir = 0; ir < this->veff->nc; ++ir)
+            // NOTICE: when MPI threads are larger than number of Z grids
+            // veff would contain nothing, and nothing should be do in real space
+            // but the 3DFFT can not be skipped, it will cause stuck
```
Comment (caic99) [inline source/module_hamilt/ks_pw/veff_pw.cpp]:
```suggestion
            // veff would contain nothing, and nothing should be done in real space
            // but the 3DFFT can not be skipped, it will cause hanging
```

**Review by caic99 — APPROVED** [review]

File: source/module_base/tool_quit.cpp [hunk 2]
```diff
@@ -128,4 +128,25 @@ void WARNING_QUIT(const std::string &file,const std::string &description)
...
+void CHECK_WARNING_QUIT(bool error_in, const std::string &file,const std::string &description)
+{
+	int error = (int)error_in;
+#ifdef __NORMAL
+// only for UT, do nothing here
+#else
+#ifdef __MPI
+	int error_max = error;
+	MPI_Reduce(&error, &error_max, 1, MPI_INT, MPI_MAX, 0, MPI_COMM_WORLD);
+	MPI_Bcast(&error_max, 1, MPI_INT, 0, MPI_COMM_WORLD);
```
Comment (Qianruipku) [inline source/module_base/tool_quit.cpp:142]: for bool type, maybe you can use 
MPI_Allreduce(MPI_IN_PLACE, &error, 1, MPI_CHAR, MPI_LOR , MPI_COMM_WORLD);

File: source/module_pw/pw_basis_k.cpp [hunk 3]
```diff
@@ -90,7 +91,12 @@ void PW_Basis_K::setupIndGk()
         {
             this->npwk_max = ng;
         }
+        if ( npwk_min > ng)
+        {
+            npwk_min = ng;
+        }
     }
+    ModuleBase::CHECK_WARNING_QUIT((npwk_min==0), "PW_Basis_K::setupIndGk", "some cores have no plane waves!");
```
Comment (Qianruipku) [inline source/module_pw/pw_basis_k.cpp:99]: We only use pool_world for pw_basis class.
pw_basis.h:
image

Comment (dyzheng) [inline source/module_pw/pw_basis_k.cpp:99]: Is pool_world different with MPI_COMM_WORLD?
We should terminate program in all processors but not only one k pool when kpar>1.

File: source/module_base/tool_quit.cpp (hunk 2 above)
Comment (dyzheng) [reply source/module_base/tool_quit.cpp:142]: Maybe you are right, but this function is very cheap, you can revise this function.
