### PR TITLE
fix: avoid nan in the output of time percentage

### LINKED ISSUE #4791: Bug: ZeroDivisionError occurs in timer in some unittests
### Describe the bug

there are some cases where the execution time of ABACUS is too short, then the calculation of percentage of functions consumed will have some ZeroDivisionError in time statistics and displays as "-nan".

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by pxlxingliang**
### Reminder
- [ ] Have you linked an issue with this pull request?
- [ ] Have you added adequate unit tests and/or case tests for your pull request?
- [ ] Have you noticed possible changes of behavior below or in the linked issue?
- [ ] Have you explained the changes of codes in core modules of ESolver, HSolver, ElecState, Hamilt, Operator or Psi? (ignore if not applicable)

### Linked Issue
Fix #4791 

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

File: source/module_base/timer.cpp [hunk 1]
```diff
@@ -255,6 +259,7 @@ void timer::print_all(std::ofstream &ofs)
 	std::vector<int> calls;
 	std::vector<double> avgs;
 	std::vector<double> pers;
+	const double TIME_EPSILON = 1e-9;
```
Comment (mohanchen) [inline source/module_base/timer.cpp]: suggst using time_epsion instead of TIME_EPSILON

Comment (mohanchen) [reply source/module_base/timer.cpp]: also, you could add some comments to explain why you choose a 1e-9 (magic number)

**Review by mohanchen — APPROVED** [review]
