### PR TITLE
Fix&Refactor: soc force/stress error for LCAO code, refactor the force/stress code into operator

### LINKED ISSUE #4884: The stress of LCAO SOC seems wrong
### Describe the bug

I have do the stress finite difference test on FeRh and NiMnTi, and the deviation between analytical stress and finite difference stress is larger than 1 kbar.

example | noncollinear + SOC | noncollinear
---|---|---
FeRh| 2be4c81e41368ee18c13c98e4dd6e712_4uXIwiJ0HsDAAAAAElFTkSuQmCC |  image 
NiMnTi |  b6696eef1d400db478aa7bd14b99381d_aMAAAAASUVORK5CYII= |  4fa4b14be6bdee6464b6a16fcb275160_zftSQd1jAAAAAElFTkSuQmCC

 

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by dyzheng**
### Linked Issue
Fix #4884 and #5328 and #5411

### Unit Tests and/or Case Tests for my changes
- A unit test is added for each new feature or bug fix.

### What's changed?
- Example: My changes might affect the performance of the application under certain conditions, and I have tested the impact on various scenarios...

### Any changes of core modules? (ignore if not applicable)
- Example: I have added a new virtual function in the esolver base class in order to ...

### CODE REVIEW

File: source/module_elecstate/module_dm/density_matrix.cpp [hunk 1]
```diff
@@ -911,6 +984,82 @@ void DensityMatrix<std::complex<double>, double>::write_DMK(const std::string di
...
+                }
+            }
+            break;
+        default:
+            throw std::string("Unknown mode in switch_dmr");
+        }
+        ModuleBase::timer::tick("DensityMatrix", "switch_dmr");
+    }
+}
+
```
Comment (mohanchen) [inline source/module_elecstate/module_dm/density_matrix.cpp:451]: I would suggest reducing the number of lines under 500.

File: source/module_elecstate/module_dm/density_matrix.h [hunk 2]
```diff
@@ -179,6 +179,8 @@ class DensityMatrix
      */
     void cal_DMR();
 
+    void cal_DMR_full(hamilt::HContainer<std::complex<double>>* dmR_out) const;
```
Comment (mohanchen) [inline source/module_elecstate/module_dm/density_matrix.h]: Add notes for the function of cal_DMR_full

File: source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp [hunk 3]
```diff
@@ -168,6 +170,52 @@ void Force_Stress_LCAO<T>::getForceStress(const bool isforce,
...
+            const_cast<elecstate::DensityMatrix<T, double>*>(dm_p)->switch_dmr(1);
+        }
+        const hamilt::HContainer<double>* dmr = dm_p->get_DMR_pointer(1);
+        tmp_nonlocal.cal_force_stress(isforce, isstress, dmr, fvnl_dbeta, svnl_dbeta);
+        if(PARAM.inp.nspin == 2)
+        {
+            const_cast<elecstate::DensityMatrix<T, double>*>(dm_p)->switch_dmr(0);
+        }
+    }
+    else
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp]: else if nspin == 4 (write clearly)

File: source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp [hunk 4]
```diff
@@ -168,6 +170,52 @@ void Force_Stress_LCAO<T>::getForceStress(const bool isforce,
                         orb,
                         pv,
                         kv);
+    // calculate force and stress for Nonlocal part
+    if(PARAM.inp.nspin != 4)
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/FORCE_STRESS.cpp]: if nspin == 1 or nspin ==2 (write clearly)

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp [hunk 5]
```diff
@@ -0,0 +1,459 @@
...
+        force.zero_out();
+    }
+    // 1. calculate <psi|beta> for each pair of atoms
+    // loop over all on-site atoms
+    int atom_index = 0;
+    for (int iat0 = 0; iat0 < this->ucell->nat; iat0++)
+    { 
+        // skip the atoms without plus-U
+        auto tau0 = ucell->get_tau(iat0);
+        int I0;
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp]: initialize the value

File: source/module_elecstate/module_dm/density_matrix_io.cpp [hunk 6]
```diff
@@ -0,0 +1,446 @@
...
+    {
+        tmp_DMR->fix_gamma();
+    }
+    tmp_DMR->allocate(nullptr, true);
+    this->_DMR.push_back(tmp_DMR);
+    // add another DMR if nspin==2
+    if (this->_nspin == 2)
+    {
+        hamilt::HContainer<TR>* tmp_DMR1;
+        tmp_DMR1 = new hamilt::HContainer<TR>(*tmp_DMR);
```
Comment (mohanchen) [inline source/module_elecstate/module_dm/density_matrix_io.cpp:62]: where is 'delete'?

File: source/module_elecstate/module_dm/density_matrix_io.cpp [hunk 7]
```diff
@@ -0,0 +1,446 @@
...
```
Comment (mohanchen) [inline source/module_elecstate/module_dm/density_matrix_io.cpp:117]: if 'delete' can not be found easily, it is dangerous

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp [hunk 8]
```diff
@@ -0,0 +1,459 @@
...
+    auto row_indexes = paraV->get_indexes_row(iat1);
+    auto col_indexes = paraV->get_indexes_col(iat2);
+    // step_trace = 0 for NSPIN=2; ={0, 1, local_col, local_col+1} for NSPIN=4
+    std::vector<int> step_trace(npol * npol, 0);
+    if (npol == 2) {
+        step_trace[1] = 1;
+        step_trace[2] = col_indexes.size();
+        step_trace[3] = col_indexes.size() + 1;
+    }
+    double tmp[3];
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp]: initialize the variables

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp [hunk 9]
```diff
@@ -0,0 +1,459 @@
...
+    auto row_indexes = paraV->get_indexes_row(iat1);
+    auto col_indexes = paraV->get_indexes_col(iat2);
+    // step_trace = 0 for NSPIN=2; ={0, 1, local_col, local_col+1} for NSPIN=4
+    std::vector<int> step_trace(npol * npol, 0);
+    if (npol == 2) {
+        step_trace[1] = 1;
+        step_trace[2] = col_indexes.size();
+        step_trace[3] = col_indexes.size() + 1;
+    }
+    double tmp[6];
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp]: initialize the variables

File: source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp [hunk 10]
```diff
@@ -0,0 +1,459 @@
...
+    // calculate the local matrix
+    const std::complex<double>* tmp_d = nullptr;
+    const std::complex<double>* dm_pointer = dmR_pointer->get_pointer();
+    for (int iw1l = 0; iw1l < row_indexes.size(); iw1l += npol)
+    {
+        const std::vector<double>& nlm1 = nlm1_all.find(row_indexes[iw1l])->second;
+        const int length = nlm1.size() / 4;
```
Comment (mohanchen) [inline source/module_hamilt_lcao/hamilt_lcaodft/operator_lcao/nonlocal_force_stress.hpp]: 4 is a magic number

File: source/module_elecstate/module_dm/density_matrix_io.cpp [hunk 11]
```diff
@@ -0,0 +1,446 @@
...
+        this->_DMR.push_back(tmp_DMR1);
+    }
+    ModuleBase::Memory::record("DensityMatrix::DMR", this->_DMR.size() * this->_DMR[0]->get_memory_size());
+}
+
+// initialize density matrix DMR from UnitCell and RA (mainly used in UnitTest)
```
Comment (mohanchen) [inline source/module_elecstate/module_dm/density_matrix_io.cpp]: use doxygen style notes

File: source/module_elecstate/module_dm/density_matrix_io.cpp [hunk 12]
```diff
@@ -0,0 +1,446 @@
...
+    }
+    this->_DMR.clear();
+    // construct a new DMR
+    hamilt::HContainer<TR>* tmp_DMR;
+    tmp_DMR = new hamilt::HContainer<TR>(this->_paraV);
+    // set up a HContainer
+    for (int iat1 = 0; iat1 < ucell->nat; iat1++)
+    {
+        auto tau1 = ucell->get_tau(iat1);
+        int T1, I1;
```
Comment (mohanchen) [inline source/module_elecstate/module_dm/density_matrix_io.cpp:86]: initialize the variables

File: source/module_elecstate/module_dm/density_matrix_io.cpp (hunk 6 above)
Comment (dyzheng) [reply source/module_elecstate/module_dm/density_matrix_io.cpp:62]: This code come from task "separate file density_matrix.cpp to avoid larger than 500 lines files", but not related with the main task "Fix" of this PR, I'm glad to discuss these code elsewhere than in this PR, the remaining issues from refactoring of "density_matrix.cpp" should not block this Fix PR.

File: source/module_elecstate/module_dm/density_matrix_io.cpp (hunk 7 above)
Comment (dyzheng) [reply source/module_elecstate/module_dm/density_matrix_io.cpp:117]: This code come from task "separate file density_matrix.cpp to avoid larger than 500 lines files", but not related with the main task "Fix" of this PR, I'm glad to discuss these code elsewhere than in this PR, the remaining issues from refactoring of "density_matrix.cpp" should not block this Fix PR.

File: source/module_elecstate/module_dm/density_matrix_io.cpp (hunk 12 above)
Comment (dyzheng) [reply source/module_elecstate/module_dm/density_matrix_io.cpp:86]: This code come from task "separate file density_matrix.cpp to avoid larger than 500 lines files", but not related with the main task "Fix" of this PR, I'm glad to discuss these code elsewhere than in this PR, the remaining issues from refactoring of "density_matrix.cpp" should not block this Fix PR.

**Review by mohanchen — APPROVED** [review]
