### PR TITLE
Fix: fix the bug which SCF restart for unconverged cases

### LINKED ISSUE #4505: Large EDIFF in last scf step suddenly
### Describe the bug

[large_de.tar.gz](https://github.com/user-attachments/files/16009984/large_de.tar.gz)
In my test case, for last scf step, EDIFF from  6.69311592e-06 jump to 3.53213141e-01 which is unnormal.
GE283    1.6800e+01   2.9235e+01  -4.82564493e+05   7.87996076e-08   2.13498468e-05 364.45
 GE284    1.6800e+01   2.9238e+01  -4.82564493e+05  -3.11050562e-06   2.12412371e-05 364.41
 GE285    1.6800e+01   2.9316e+01  -4.82564493e+05   1.00953583e-05   2.07483494e-05 364.14
 GE286    1.6800e+01   2.9303e+01  -4.82564493e+05  -2.09598047e-05   2.07266596e-05 364.02
 GE287    1.6800e+01   2.9395e+01  -4.82564493e+05  -9.55267053e-06   2.03377062e-05 364.47
 GE288    1.6800e+01   2.9363e+01  -4.82564493e+05  -3.70150267e-06   2.05601797e-05 364.45
 GE289    1.6800e+01   2.9402e+01  -4.82564493e+05  -6.87110800e-06   2.01517282e-05 364.28
 GE290    1.6800e+01   2.9417e+01  -4.82564493e+05  -6.01094494e-07   2.00977701e-05 364.16
 GE291    1.6800e+01   2.9413e+01  -4.82564493e+05  -3.82435483e-06   2.00485653e-05 363.75
 GE292    1.6800e+01   2.9447e+01  -4.82564493e+05   3.19969965e-06   2.02117045e-05 364.06
 GE293    1.6800e+01   2.9424e+01  -4.82564493e+05  -4.66937173e-06   2.02269025e-05 364.26
 GE294    1.6800e+01   2.9480e+01  -4.82564493e+05   1.81912260e-06   2.01544955e-05 364.38
 GE295    1.6800e+01   2.9605e+01  -4.82564493e+05  -2.69545145e-05   1.99719187e-05 364.41
 GE296    1.6800e+01   2.9624e+01  -4.82564493e+05  -1.03393797e-05   2.00034318e-05 364.40
 GE297    1.6800e+01   2.9667e+01  -4.82564493e+05  -4.54493566e-06   2.01031835e-05 364.16
 GE298    1.6800e+01   2.9664e+01  -4.82564493e+05   5.73633425e-06   2.01218804e-05 364.17
 GE299    1.6800e+01   2.9640e+01  -4.82564493e+05   6.69311592e-06   2.01431092e-05 364.44
 GE300    1.6800e+01   2.9608e+01  -4.82564140e+05   3.53213141e-01   2.01885897e-05 364.30
 >> Leave SCF iteration.
 * * * * * *
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!
TIME STATISTICS

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

### PR DESCRIPTION
**Pull request by WHUweiqingzhou**
Fix #4505.

### CODE REVIEW

**Review by pxlxingliang — APPROVED** [review]

File: source/module_esolver/esolver_ks.cpp [hunk 1]
```diff
@@ -382,49 +380,75 @@ void ESolver_KS<T, Device>::hamilt2density(const int istep, const int iter, cons
 //! mohan add 2024-05-11
 //------------------------------------------------------------------------------
 template <typename T, typename Device>
-void ESolver_KS<T, Device>::print_wfcfft(Input& inp, std::ofstream& ofs)
-{
+void ESolver_KS<T, Device>::print_wfcfft(Input& inp, std::ofstream& ofs) {
     ofs << "\n\n\n\n";
```
Comment (WHUweiqingzhou) [inline source/module_esolver/esolver_ks.cpp:384]: @haozhihan could we remove this rule from clang-format?

Comment (mohanchen) [reply source/module_esolver/esolver_ks.cpp:384]: I think so, should do this asap.

**Review by mohanchen — APPROVED** [review]
