### PR TITLE
fix: set defualt of bx/y/z to 1 when calculation is get_wf

### LINKED ISSUE #2656: run abacus-develop/examples/wfc/lcao_ienvelope_Si2 fail
### Describe the bug

Run second step of abacus-develop/examples/wfc/lcao_ienvelope_Si2 fail, and the error message is :

```
 ---------------------------------------------------------
 ---------------------------------------------------------
 SPIN    KPOINTS         PROCESSORS  NBASE       
 1       36              4           26          
 ---------------------------------------------------------
 Use Systematically Improvable Atomic bases
 ---------------------------------------------------------
 ELEMENT ORBITALS        NBASE       NATOM       XC          
 Si      2s2p1d-8au      13          2           
 ---------------------------------------------------------
 Initial plane wave basis and FFT box
 ---------------------------------------------------------

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 81580 RUNNING AT 790742b7e6fb
=   KILLED BY SIGNAL: 8 (Floating point exception)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 81581 RUNNING AT 790742b7e6fb
=   KILLED BY SIGNAL: 8 (Floating point exception)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 81582 RUNNING AT 790742b7e6fb
=   KILLED BY SIGNAL: 8 (Floating point exception)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 81583 RUNNING AT 790742b7e6fb
=   KILLED BY SIGNAL: 8 (Floating point exception)
===================================================================================
```

### Expected behavior

_No response_

### To Reproduce

_No response_

### Environment

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by pxlxingliang**
fix #2656

### CODE REVIEW

File: source/module_io/input.cpp [hunk 1]
```diff
@@ -2706,6 +2706,18 @@ void Input::Default_2(void) // jiyy add 2019-08-04
             lcao_ecut = ecutwfc;
             ModuleBase::GlobalFunc::AUTO_SET("lcao_ecut", ecutwfc);
         }
+
+        // if calculation is get_wf, function source/module_basis/module_pw/pw_basis_k_big.h/distribute_r()
+        // will calculate nbx/nby/nbz by divide nx/ny/nz by bx/by/bz, so bx/by/bz should not be 0
+        if (calculation == "get_wf")
```
Comment (dyzheng) [inline source/module_io/input.cpp:2712]: Thanks for your contribution, it can solve the related issue.
To be honest, I think it is not reasonable to use bx/by/bz in get_wf calculation.

**Review by dyzheng — APPROVED** [review]
